# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class guiMNPS(object):
    def setupUi(self, winMNPS):
        winMNPS.setObjectName("winMNPS")
        winMNPS.resize(480, 320)
        winMNPS.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.lblUnits_2 = QtWidgets.QLabel(winMNPS)
        self.lblUnits_2.setGeometry(QtCore.QRect(330, 90, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lblUnits_2.setFont(font)
        self.lblUnits_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblUnits_2.setObjectName("lblUnits_2")
        self.lblDurationinfo = QtWidgets.QLabel(winMNPS)
        self.lblDurationinfo.setGeometry(QtCore.QRect(210, 50, 81, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblDurationinfo.setFont(font)
        self.lblDurationinfo.setStyleSheet("color: rgb(255, 0, 0);")
        self.lblDurationinfo.setObjectName("lblDurationinfo")
        self.lblLFmin = QtWidgets.QLabel(winMNPS)
        self.lblLFmin.setGeometry(QtCore.QRect(260, 220, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblLFmin.setFont(font)
        self.lblLFmin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLFmin.setObjectName("lblLFmin")
        self.lcdLFmin = QtWidgets.QLabel(winMNPS)
        self.lcdLFmin.setGeometry(QtCore.QRect(320, 220, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lcdLFmin.setFont(font)
        self.lcdLFmin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLFmin.setObjectName("lcdLFmin")
        self.btnStop = QtWidgets.QPushButton(winMNPS)
        self.btnStop.setGeometry(QtCore.QRect(410, 30, 60, 55))
        self.btnStop.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnStop.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/Stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon)
        self.btnStop.setIconSize(QtCore.QSize(60, 55))
        self.btnStop.setObjectName("btnStop")
        self.lblLSmax = QtWidgets.QLabel(winMNPS)
        self.lblLSmax.setGeometry(QtCore.QRect(110, 270, 56, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lblLSmax.setFont(font)
        self.lblLSmax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLSmax.setObjectName("lblLSmax")
        self.lcdLSmax = QtWidgets.QLabel(winMNPS)
        self.lcdLSmax.setGeometry(QtCore.QRect(170, 270, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lcdLSmax.setFont(font)
        self.lcdLSmax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLSmax.setObjectName("lcdLSmax")
        self.lcdLSmin = QtWidgets.QLabel(winMNPS)
        self.lcdLSmin.setGeometry(QtCore.QRect(320, 270, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lcdLSmin.setFont(font)
        self.lcdLSmin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLSmin.setObjectName("lcdLSmin")
        self.lcdLImax = QtWidgets.QLabel(winMNPS)
        self.lcdLImax.setGeometry(QtCore.QRect(170, 170, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lcdLImax.setFont(font)
        self.lcdLImax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLImax.setObjectName("lcdLImax")
        self.lblMinLevel_3 = QtWidgets.QLabel(winMNPS)
        self.lblMinLevel_3.setGeometry(QtCore.QRect(360, 220, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblMinLevel_3.setFont(font)
        self.lblMinLevel_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblMinLevel_3.setObjectName("lblMinLevel_3")
        self.lblLSmin = QtWidgets.QLabel(winMNPS)
        self.lblLSmin.setGeometry(QtCore.QRect(260, 270, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblLSmin.setFont(font)
        self.lblLSmin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLSmin.setObjectName("lblLSmin")
        self.lblMaxLevel_3 = QtWidgets.QLabel(winMNPS)
        self.lblMaxLevel_3.setGeometry(QtCore.QRect(220, 220, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblMaxLevel_3.setFont(font)
        self.lblMaxLevel_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblMaxLevel_3.setObjectName("lblMaxLevel_3")
        self.lblMaxLevel_4 = QtWidgets.QLabel(winMNPS)
        self.lblMaxLevel_4.setGeometry(QtCore.QRect(220, 270, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblMaxLevel_4.setFont(font)
        self.lblMaxLevel_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblMaxLevel_4.setObjectName("lblMaxLevel_4")
        self.lcdLevel_global = QtWidgets.QLabel(winMNPS)
        self.lcdLevel_global.setGeometry(QtCore.QRect(200, 90, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lcdLevel_global.setFont(font)
        self.lcdLevel_global.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLevel_global.setObjectName("lcdLevel_global")
        self.btnSave = QtWidgets.QPushButton(winMNPS)
        self.btnSave.setGeometry(QtCore.QRect(30, 120, 40, 40))
        self.btnSave.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnSave.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon1)
        self.btnSave.setIconSize(QtCore.QSize(40, 40))
        self.btnSave.setObjectName("btnSave")
        self.lblMaxLevel_2 = QtWidgets.QLabel(winMNPS)
        self.lblMaxLevel_2.setGeometry(QtCore.QRect(220, 170, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblMaxLevel_2.setFont(font)
        self.lblMaxLevel_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblMaxLevel_2.setObjectName("lblMaxLevel_2")
        self.lcdLFmax = QtWidgets.QLabel(winMNPS)
        self.lcdLFmax.setGeometry(QtCore.QRect(170, 220, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lcdLFmax.setFont(font)
        self.lcdLFmax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLFmax.setObjectName("lcdLFmax")
        self.lblMinLevel_2 = QtWidgets.QLabel(winMNPS)
        self.lblMinLevel_2.setGeometry(QtCore.QRect(360, 170, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblMinLevel_2.setFont(font)
        self.lblMinLevel_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblMinLevel_2.setObjectName("lblMinLevel_2")
        self.lblLFmax = QtWidgets.QLabel(winMNPS)
        self.lblLFmax.setGeometry(QtCore.QRect(110, 220, 56, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lblLFmax.setFont(font)
        self.lblLFmax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLFmax.setObjectName("lblLFmax")
        self.lcdLImin = QtWidgets.QLabel(winMNPS)
        self.lcdLImin.setGeometry(QtCore.QRect(320, 170, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lcdLImin.setFont(font)
        self.lcdLImin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLImin.setObjectName("lcdLImin")
        self.lblMinLevel_4 = QtWidgets.QLabel(winMNPS)
        self.lblMinLevel_4.setGeometry(QtCore.QRect(360, 270, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblMinLevel_4.setFont(font)
        self.lblMinLevel_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblMinLevel_4.setObjectName("lblMinLevel_4")
        self.btnPlay = QtWidgets.QPushButton(winMNPS)
        self.btnPlay.setGeometry(QtCore.QRect(20, 30, 60, 55))
        self.btnPlay.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnPlay.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icon/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlay.setIcon(icon2)
        self.btnPlay.setIconSize(QtCore.QSize(60, 55))
        self.btnPlay.setObjectName("btnPlay")
        self.lblLImax = QtWidgets.QLabel(winMNPS)
        self.lblLImax.setGeometry(QtCore.QRect(110, 170, 56, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lblLImax.setFont(font)
        self.lblLImax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLImax.setObjectName("lblLImax")
        self.btnDelete = QtWidgets.QPushButton(winMNPS)
        self.btnDelete.setGeometry(QtCore.QRect(420, 120, 40, 40))
        self.btnDelete.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnDelete.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/Delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon3)
        self.btnDelete.setIconSize(QtCore.QSize(40, 40))
        self.btnDelete.setObjectName("btnDelete")
        self.lblUnits = QtWidgets.QLabel(winMNPS)
        self.lblUnits.setGeometry(QtCore.QRect(110, 90, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lblUnits.setFont(font)
        self.lblUnits.setWhatsThis("")
        self.lblUnits.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblUnits.setObjectName("lblUnits")
        self.lblLImin = QtWidgets.QLabel(winMNPS)
        self.lblLImin.setGeometry(QtCore.QRect(260, 170, 56, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblLImin.setFont(font)
        self.lblLImin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLImin.setObjectName("lblLImin")
        self.lblProjectinfo = QtWidgets.QLabel(winMNPS)
        self.lblProjectinfo.setGeometry(QtCore.QRect(130, 20, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblProjectinfo.setFont(font)
        self.lblProjectinfo.setWhatsThis("")
        self.lblProjectinfo.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblProjectinfo.setObjectName("lblProjectinfo")
        self.btnSetup = QtWidgets.QPushButton(winMNPS)
        self.btnSetup.setGeometry(QtCore.QRect(30, 260, 40, 40))
        self.btnSetup.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnSetup.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icon/Setup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSetup.setIcon(icon4)
        self.btnSetup.setIconSize(QtCore.QSize(40, 40))
        self.btnSetup.setObjectName("btnSetup")
        self.btnQuit = QtWidgets.QPushButton(winMNPS)
        self.btnQuit.setGeometry(QtCore.QRect(420, 260, 40, 40))
        self.btnQuit.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnQuit.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Sound-Level-Meter/icon/power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnQuit.setIcon(icon5)
        self.btnQuit.setIconSize(QtCore.QSize(40, 40))
        self.btnQuit.setObjectName("btnQuit")
        self.lblUnits_2.raise_()
        self.lblDurationinfo.raise_()
        self.lblLFmin.raise_()
        self.lcdLFmin.raise_()
        self.btnStop.raise_()
        self.lblLSmax.raise_()
        self.lcdLSmax.raise_()
        self.lcdLSmin.raise_()
        self.lcdLImax.raise_()
        self.lblMinLevel_3.raise_()
        self.lblLSmin.raise_()
        self.lblMaxLevel_3.raise_()
        self.lblMaxLevel_4.raise_()
        self.lcdLevel_global.raise_()
        self.btnSave.raise_()
        self.lblMaxLevel_2.raise_()
        self.lcdLFmax.raise_()
        self.lblLFmax.raise_()
        self.lcdLImin.raise_()
        self.lblMinLevel_4.raise_()
        self.btnPlay.raise_()
        self.lblLImax.raise_()
        self.btnDelete.raise_()
        self.lblUnits.raise_()
        self.lblLImin.raise_()
        self.lblProjectinfo.raise_()
        self.btnSetup.raise_()
        self.btnQuit.raise_()
        self.lblMinLevel_2.raise_()

        self.retranslateUi(winMNPS)
        QtCore.QMetaObject.connectSlotsByName(winMNPS)

    def retranslateUi(self, winMNPS, inFreqweighting='Z', inTimeweighting='S'):
        _translate = QtCore.QCoreApplication.translate
        winMNPS.setWindowTitle(_translate("winMNPS", "Sonômetro EAC"))
        self.lblUnits_2.setText(_translate("winMNPS", "dB"))
        self.lblDurationinfo.setText(_translate("winMNPS", "Min:Sec"))
        self.lblLFmin.setText(_translate("winMNPS", "<html><head/><body><p><span style=\" font-size:14pt;\">L</span><span style=\" font-size:14pt; vertical-align:sub;\">"+inFreqweighting+"min,F</span></p></body></html>"))
        self.lcdLFmin.setText(_translate("winMNPS", "--,--"))
        self.lblLSmax.setText(_translate("winMNPS", "<html><head/><body><p><span style=\" font-size:14pt;\">L</span><span style=\" font-size:14pt; vertical-align:sub;\">"+inFreqweighting+"max,S</span></p></body></html>"))
        self.lcdLSmax.setText(_translate("winMNPS", "--,--"))
        self.lcdLSmin.setText(_translate("winMNPS", "--,--"))
        self.lcdLImax.setText(_translate("winMNPS", "--,--"))
        self.lblMinLevel_3.setText(_translate("winMNPS", " dB"))
        self.lblLSmin.setText(_translate("winMNPS", "<html><head/><body><p><span style=\" font-size:14pt;\">L</span><span style=\" font-size:14pt; vertical-align:sub;\">"+inFreqweighting+"min,S</span></p></body></html>"))
        self.lblMaxLevel_3.setText(_translate("winMNPS", " dB"))
        self.lblMaxLevel_4.setText(_translate("winMNPS", " dB"))
        self.lcdLevel_global.setText(_translate("winMNPS", "00,00"))
        self.lblMaxLevel_2.setText(_translate("winMNPS", " dB"))
        self.lcdLFmax.setText(_translate("winMNPS", "--,--"))
        self.lblMinLevel_2.setText(_translate("winMNPS", " dB"))
        self.lblLFmax.setText(_translate("winMNPS", "<html><head/><body><p><span style=\" font-size:14pt;\">L</span><span style=\" font-size:14pt; vertical-align:sub;\">"+inFreqweighting+"max,F</span></p></body></html>"))
        self.lcdLImin.setText(_translate("winMNPS", "--,--"))
        self.lblMinLevel_4.setText(_translate("winMNPS", " dB"))
        self.lblLImax.setText(_translate("winMNPS", "<html><head/><body><p><span style=\" font-size:14pt;\">L</span><span style=\" font-size:14pt; vertical-align:sub;\">"+inFreqweighting+"max,I</span></p></body></html>"))
        self.lblUnits.setText(_translate("winMNPS", "<html><head/><body><p>L<span style=\" vertical-align:sub;\">"+inFreqweighting+"eq,"+inTimeweighting+"</span></p></body></html>"))
        self.lblLImin.setText(_translate("winMNPS", "<html><head/><body><p><span style=\" font-size:14pt;\">L</span><span style=\" font-size:14pt; vertical-align:sub;\">"+inFreqweighting+"min,I</span></p></body></html>"))
        self.lblProjectinfo.setText(_translate("winMNPS", "<html><head/><body><p align=\"center\">Project name - Measurement 00</p></body></html>"))


class guiSetup(object):
    def setupUi(self, winSetup):
        winSetup.setObjectName("winSetup")
        winSetup.setEnabled(True)
        winSetup.resize(480, 320)
        winSetup.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.lbl_Duration_AnalEspec = QtWidgets.QLabel(winSetup)
        self.lbl_Duration_AnalEspec.setGeometry(QtCore.QRect(10, 102, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Duration_AnalEspec.setFont(font)
        self.lbl_Duration_AnalEspec.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_Duration_AnalEspec.setObjectName("lbl_Duration_AnalEspec")
        self.lblTimeintegration = QtWidgets.QLabel(winSetup)
        self.lblTimeintegration.setGeometry(QtCore.QRect(10, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblTimeintegration.setFont(font)
        self.lblTimeintegration.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblTimeintegration.setObjectName("lblTimeintegration")
        self.btnCancel = QtWidgets.QPushButton(winSetup)
        self.btnCancel.setGeometry(QtCore.QRect(30, 260, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("background-color: none;")
        self.btnCancel.setObjectName("btnCancel")
        self.lblPondfreq = QtWidgets.QLabel(winSetup)
        self.lblPondfreq.setGeometry(QtCore.QRect(10, 182, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblPondfreq.setFont(font)
        self.lblPondfreq.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblPondfreq.setObjectName("lblPondfreq")
        self.frameCalibration = QtWidgets.QFrame(winSetup)
        self.frameCalibration.setGeometry(QtCore.QRect(330, 10, 141, 131))
        self.frameCalibration.setStyleSheet("background-color: rgb(82, 255, 235);")
        self.frameCalibration.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCalibration.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCalibration.setObjectName("frameCalibration")
        self.btnCalibrate = QtWidgets.QPushButton(self.frameCalibration)
        self.btnCalibrate.setGeometry(QtCore.QRect(20, 80, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnCalibrate.setFont(font)
        self.btnCalibrate.setStyleSheet("background-color: none;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/Calibrate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCalibrate.setIcon(icon)
        self.btnCalibrate.setIconSize(QtCore.QSize(35, 35))
        self.btnCalibrate.setObjectName("btnCalibrate")
        self.lblFTCalibration = QtWidgets.QLabel(self.frameCalibration)
        self.lblFTCalibration.setGeometry(QtCore.QRect(23, 2, 85, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblFTCalibration.setFont(font)
        self.lblFTCalibration.setObjectName("lblFTCalibration")
        self.lblFTC = QtWidgets.QLabel(self.frameCalibration)
        self.lblFTC.setGeometry(QtCore.QRect(19, 37, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblFTC.setFont(font)
        self.lblFTC.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFTC.setObjectName("lblFTC")
        self.btnApply = QtWidgets.QPushButton(winSetup)
        self.btnApply.setGeometry(QtCore.QRect(200, 260, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnApply.setFont(font)
        self.btnApply.setStyleSheet("background-color: none;")
        self.btnApply.setObjectName("btnApply")
        self.frame_inTimeweighting = QtWidgets.QFrame(winSetup)
        self.frame_inTimeweighting.setGeometry(QtCore.QRect(212, 11, 101, 40))
        self.frame_inTimeweighting.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_inTimeweighting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inTimeweighting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inTimeweighting.setObjectName("frame_inTimeweighting")
        self.inTimeweighting = QtWidgets.QComboBox(self.frame_inTimeweighting)
        self.inTimeweighting.setGeometry(QtCore.QRect(0, 0, 101, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inTimeweighting.setFont(font)
        self.inTimeweighting.setStyleSheet("background-color: none;")
        self.inTimeweighting.setObjectName("inTimeweighting")
        self.inTimeweighting.addItem("")
        self.inTimeweighting.addItem("")
        self.inTimeweighting.addItem("")
        self.frame_inFreqweighting = QtWidgets.QFrame(winSetup)
        self.frame_inFreqweighting.setGeometry(QtCore.QRect(213, 172, 101, 40))
        self.frame_inFreqweighting.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_inFreqweighting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inFreqweighting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inFreqweighting.setObjectName("frame_inFreqweighting")
        self.inFreqweighting = QtWidgets.QComboBox(self.frame_inFreqweighting)
        self.inFreqweighting.setGeometry(QtCore.QRect(0, 0, 101, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inFreqweighting.setFont(font)
        self.inFreqweighting.setStyleSheet("background-color: none;")
        self.inFreqweighting.setObjectName("inFreqweighting")
        self.inFreqweighting.addItem("")
        self.inFreqweighting.addItem("")
        self.inFreqweighting.addItem("")
        self.inDurationMeasure = QtWidgets.QTimeEdit(winSetup)
        self.inDurationMeasure.setGeometry(QtCore.QRect(213, 90, 101, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inDurationMeasure.setFont(font)
        self.inDurationMeasure.setStyleSheet("background-color: None")
        self.inDurationMeasure.setMaximumTime(QtCore.QTime(0, 59, 59))
        self.inDurationMeasure.setMinimumTime(QtCore.QTime(0, 0, 20))
        self.inDurationMeasure.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.inDurationMeasure.setObjectName("inDurationMeasure")
        self.btnNewproject = QtWidgets.QPushButton(winSetup)
        self.btnNewproject.setGeometry(QtCore.QRect(330, 160, 141, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnNewproject.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnNewproject.setFont(font)
        self.btnNewproject.setStyleSheet("background-color: rgb(172, 229, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/NewProject.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewproject.setIcon(icon1)
        self.btnNewproject.setIconSize(QtCore.QSize(35, 35))
        self.btnNewproject.setObjectName("btnNewproject")
        self.btnInfo = QtWidgets.QPushButton(winSetup)
        self.btnInfo.setGeometry(QtCore.QRect(330, 220, 141, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnInfo.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnInfo.setFont(font)
        self.btnInfo.setStyleSheet("background-color: rgb(172, 229, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInfo.setIcon(icon2)
        self.btnInfo.setIconSize(QtCore.QSize(35, 35))
        self.btnInfo.setObjectName("btnInfo")

        self.retranslateUi(winSetup)
        QtCore.QMetaObject.connectSlotsByName(winSetup)

    def retranslateUi(self, winSetup):
        _translate = QtCore.QCoreApplication.translate
        winSetup.setWindowTitle(_translate("winSetup", "Settings"))
        self.lbl_Duration_AnalEspec.setText(_translate("winSetup", "Duration:"))
        self.lblTimeintegration.setText(_translate("winSetup", "Time weighting:"))
        self.btnCancel.setText(_translate("winSetup", "Cancel"))
        self.lblPondfreq.setText(_translate("winSetup", "Frequency weighting:"))
        self.btnCalibrate.setText(_translate("winSetup", "Calibrate   "))
        self.lblFTCalibration.setText(_translate("winSetup", "Correction:"))
        self.lblFTC.setText(_translate("winSetup", "100,00 dB"))
        self.btnApply.setText(_translate("winSetup", "Apply"))
        self.inTimeweighting.setItemText(0, _translate("winSetup", "Impulse"))
        self.inTimeweighting.setItemText(1, _translate("winSetup", "Fast"))
        self.inTimeweighting.setItemText(2, _translate("winSetup", "Slow"))
        self.inFreqweighting.setItemText(0, _translate("winSetup", "A"))
        self.inFreqweighting.setItemText(1, _translate("winSetup", "C"))
        self.inFreqweighting.setItemText(2, _translate("winSetup", "Z"))
        self.inDurationMeasure.setDisplayFormat(_translate("winSetup", "mm:ss"))
        self.btnNewproject.setText(_translate("winSetup", "New project"))
        self.btnInfo.setText(_translate("winSetup", "About              "))


class guiProject(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 317)
        Dialog.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.lblNovoProjeto = QtWidgets.QLabel(Dialog)
        self.lblNovoProjeto.setGeometry(QtCore.QRect(160, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lblNovoProjeto.setFont(font)
        self.lblNovoProjeto.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblNovoProjeto.setObjectName("lblNovoProjeto")
        self.lblNome = QtWidgets.QLabel(Dialog)
        self.lblNome.setGeometry(QtCore.QRect(10, 60, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblNome.setFont(font)
        self.lblNome.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblNome.setObjectName("lblNome")
        self.entryProjectname = QtWidgets.QTextEdit(Dialog)
        self.entryProjectname.setGeometry(QtCore.QRect(80, 60, 341, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.entryProjectname.setFont(font)
        self.entryProjectname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryProjectname.setObjectName("entryProjectname")
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(10, 249, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("background-color: None;")
        self.btnCancel.setObjectName("btnCancel")
        self.btnCreate = QtWidgets.QPushButton(Dialog)
        self.btnCreate.setGeometry(QtCore.QRect(340, 249, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCreate.setFont(font)
        self.btnCreate.setStyleSheet("background-color: None;")
        self.btnCreate.setObjectName("btnCreate")
        self.vk_q = QtWidgets.QPushButton(Dialog)
        self.vk_q.setGeometry(QtCore.QRect(10, 159, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_q.setFont(font)
        self.vk_q.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_q.setMouseTracking(False)
        # self.vk_q.setTabletTracking(False)
        self.vk_q.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_q.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_q.setAccessibleName("")
        self.vk_q.setAutoFillBackground(False)
        self.vk_q.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_q.setObjectName("vk_q")
        self.vk_w = QtWidgets.QPushButton(Dialog)
        self.vk_w.setGeometry(QtCore.QRect(56, 159, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_w.setFont(font)
        self.vk_w.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_w.setMouseTracking(False)
        # self.vk_w.setTabletTracking(False)
        self.vk_w.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_w.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_w.setAccessibleName("")
        self.vk_w.setAutoFillBackground(False)
        self.vk_w.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_w.setObjectName("vk_w")
        self.vk_e = QtWidgets.QPushButton(Dialog)
        self.vk_e.setGeometry(QtCore.QRect(104, 159, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_e.setFont(font)
        self.vk_e.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_e.setMouseTracking(False)
        # self.vk_e.setTabletTracking(False)
        self.vk_e.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_e.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_e.setAccessibleName("")
        self.vk_e.setAutoFillBackground(False)
        self.vk_e.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_e.setObjectName("vk_e")
        self.vk_r = QtWidgets.QPushButton(Dialog)
        self.vk_r.setGeometry(QtCore.QRect(150, 159, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_r.setFont(font)
        self.vk_r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_r.setMouseTracking(False)
        # self.vk_r.setTabletTracking(False)
        self.vk_r.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_r.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_r.setAccessibleName("")
        self.vk_r.setAutoFillBackground(False)
        self.vk_r.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_r.setObjectName("vk_r")
        self.vk_t = QtWidgets.QPushButton(Dialog)
        self.vk_t.setGeometry(QtCore.QRect(197, 159, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_t.setFont(font)
        self.vk_t.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_t.setMouseTracking(False)
        # self.vk_t.setTabletTracking(False)
        self.vk_t.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_t.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_t.setAccessibleName("")
        self.vk_t.setAutoFillBackground(False)
        self.vk_t.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_t.setObjectName("vk_t")
        self.vk_y = QtWidgets.QPushButton(Dialog)
        self.vk_y.setGeometry(QtCore.QRect(244, 159, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_y.setFont(font)
        self.vk_y.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_y.setMouseTracking(False)
        # self.vk_y.setTabletTracking(False)
        self.vk_y.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_y.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_y.setAccessibleName("")
        self.vk_y.setAutoFillBackground(False)
        self.vk_y.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_y.setObjectName("vk_y")
        self.vk_u = QtWidgets.QPushButton(Dialog)
        self.vk_u.setGeometry(QtCore.QRect(290, 159, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_u.setFont(font)
        self.vk_u.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_u.setMouseTracking(False)
        # self.vk_u.setTabletTracking(False)
        self.vk_u.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_u.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_u.setAccessibleName("")
        self.vk_u.setAutoFillBackground(False)
        self.vk_u.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_u.setObjectName("vk_u")
        self.vk_p = QtWidgets.QPushButton(Dialog)
        self.vk_p.setGeometry(QtCore.QRect(430, 159, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_p.setFont(font)
        self.vk_p.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_p.setMouseTracking(False)
        # self.vk_p.setTabletTracking(False)
        self.vk_p.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_p.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_p.setAccessibleName("")
        self.vk_p.setAutoFillBackground(False)
        self.vk_p.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_p.setObjectName("vk_p")
        self.vk_a = QtWidgets.QPushButton(Dialog)
        self.vk_a.setGeometry(QtCore.QRect(10, 189, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_a.setFont(font)
        self.vk_a.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_a.setMouseTracking(False)
        # self.vk_a.setTabletTracking(False)
        self.vk_a.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_a.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_a.setAccessibleName("")
        self.vk_a.setAutoFillBackground(False)
        self.vk_a.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_a.setObjectName("vk_a")
        self.vk_s = QtWidgets.QPushButton(Dialog)
        self.vk_s.setGeometry(QtCore.QRect(56, 189, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_s.setFont(font)
        self.vk_s.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_s.setMouseTracking(False)
        # self.vk_s.setTabletTracking(False)
        self.vk_s.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_s.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_s.setAccessibleName("")
        self.vk_s.setAutoFillBackground(False)
        self.vk_s.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_s.setObjectName("vk_s")
        self.vk_i = QtWidgets.QPushButton(Dialog)
        self.vk_i.setGeometry(QtCore.QRect(338, 159, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_i.setFont(font)
        self.vk_i.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_i.setMouseTracking(False)
        # self.vk_i.setTabletTracking(False)
        self.vk_i.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_i.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_i.setAccessibleName("")
        self.vk_i.setAutoFillBackground(False)
        self.vk_i.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_i.setObjectName("vk_i")
        self.vk_o = QtWidgets.QPushButton(Dialog)
        self.vk_o.setGeometry(QtCore.QRect(384, 159, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_o.setFont(font)
        self.vk_o.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_o.setMouseTracking(False)
        # self.vk_o.setTabletTracking(False)
        self.vk_o.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_o.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_o.setAccessibleName("")
        self.vk_o.setAutoFillBackground(False)
        self.vk_o.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_o.setObjectName("vk_o")
        self.vk_d = QtWidgets.QPushButton(Dialog)
        self.vk_d.setGeometry(QtCore.QRect(104, 189, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_d.setFont(font)
        self.vk_d.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_d.setMouseTracking(False)
        # self.vk_d.setTabletTracking(False)
        self.vk_d.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_d.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_d.setAccessibleName("")
        self.vk_d.setAutoFillBackground(False)
        self.vk_d.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_d.setObjectName("vk_d")
        self.vk_f = QtWidgets.QPushButton(Dialog)
        self.vk_f.setGeometry(QtCore.QRect(150, 189, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_f.setFont(font)
        self.vk_f.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_f.setMouseTracking(False)
        # self.vk_f.setTabletTracking(False)
        self.vk_f.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_f.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_f.setAccessibleName("")
        self.vk_f.setAutoFillBackground(False)
        self.vk_f.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_f.setObjectName("vk_f")
        self.vk_j = QtWidgets.QPushButton(Dialog)
        self.vk_j.setGeometry(QtCore.QRect(290, 189, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_j.setFont(font)
        self.vk_j.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_j.setMouseTracking(False)
        # self.vk_j.setTabletTracking(False)
        self.vk_j.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_j.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_j.setAccessibleName("")
        self.vk_j.setAutoFillBackground(False)
        self.vk_j.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_j.setObjectName("vk_j")
        self.vk_k = QtWidgets.QPushButton(Dialog)
        self.vk_k.setGeometry(QtCore.QRect(338, 189, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_k.setFont(font)
        self.vk_k.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_k.setMouseTracking(False)
        # self.vk_k.setTabletTracking(False)
        self.vk_k.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_k.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_k.setAccessibleName("")
        self.vk_k.setAutoFillBackground(False)
        self.vk_k.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_k.setObjectName("vk_k")
        self.vk_l = QtWidgets.QPushButton(Dialog)
        self.vk_l.setGeometry(QtCore.QRect(384, 189, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_l.setFont(font)
        self.vk_l.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_l.setMouseTracking(False)
        # self.vk_l.setTabletTracking(False)
        self.vk_l.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_l.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_l.setAccessibleName("")
        self.vk_l.setAutoFillBackground(False)
        self.vk_l.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_l.setObjectName("vk_l")
        self.vk_g = QtWidgets.QPushButton(Dialog)
        self.vk_g.setGeometry(QtCore.QRect(197, 189, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_g.setFont(font)
        self.vk_g.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_g.setMouseTracking(False)
        # self.vk_g.setTabletTracking(False)
        self.vk_g.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_g.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_g.setAccessibleName("")
        self.vk_g.setAutoFillBackground(False)
        self.vk_g.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_g.setObjectName("vk_g")
        self.vk_h = QtWidgets.QPushButton(Dialog)
        self.vk_h.setGeometry(QtCore.QRect(244, 189, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_h.setFont(font)
        self.vk_h.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_h.setMouseTracking(False)
        # self.vk_h.setTabletTracking(False)
        self.vk_h.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_h.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_h.setAccessibleName("")
        self.vk_h.setAutoFillBackground(False)
        self.vk_h.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_h.setObjectName("vk_h")
        self.vk_cc = QtWidgets.QPushButton(Dialog)
        self.vk_cc.setGeometry(QtCore.QRect(430, 189, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_cc.setFont(font)
        self.vk_cc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_cc.setMouseTracking(False)
        # self.vk_cc.setTabletTracking(False)
        self.vk_cc.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_cc.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_cc.setAccessibleName("")
        self.vk_cc.setAutoFillBackground(False)
        self.vk_cc.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_cc.setObjectName("vk_cc")
        self.vk_z = QtWidgets.QPushButton(Dialog)
        self.vk_z.setGeometry(QtCore.QRect(10, 219, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_z.setFont(font)
        self.vk_z.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_z.setMouseTracking(False)
        # self.vk_z.setTabletTracking(False)
        self.vk_z.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_z.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_z.setAccessibleName("")
        self.vk_z.setAutoFillBackground(False)
        self.vk_z.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_z.setObjectName("vk_z")
        self.vk_c = QtWidgets.QPushButton(Dialog)
        self.vk_c.setGeometry(QtCore.QRect(104, 219, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_c.setFont(font)
        self.vk_c.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_c.setMouseTracking(False)
        # self.vk_c.setTabletTracking(False)
        self.vk_c.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_c.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_c.setAccessibleName("")
        self.vk_c.setAutoFillBackground(False)
        self.vk_c.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_c.setObjectName("vk_c")
        self.vk_n = QtWidgets.QPushButton(Dialog)
        self.vk_n.setGeometry(QtCore.QRect(244, 219, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_n.setFont(font)
        self.vk_n.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_n.setMouseTracking(False)
        # self.vk_n.setTabletTracking(False)
        self.vk_n.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_n.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_n.setAccessibleName("")
        self.vk_n.setAutoFillBackground(False)
        self.vk_n.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_n.setObjectName("vk_n")
        self.vk_x = QtWidgets.QPushButton(Dialog)
        self.vk_x.setGeometry(QtCore.QRect(56, 219, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_x.setFont(font)
        self.vk_x.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_x.setMouseTracking(False)
        # self.vk_x.setTabletTracking(False)
        self.vk_x.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_x.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_x.setAccessibleName("")
        self.vk_x.setAutoFillBackground(False)
        self.vk_x.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_x.setObjectName("vk_x")
        self.vk_v = QtWidgets.QPushButton(Dialog)
        self.vk_v.setGeometry(QtCore.QRect(150, 219, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_v.setFont(font)
        self.vk_v.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_v.setMouseTracking(False)
        # self.vk_v.setTabletTracking(False)
        self.vk_v.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_v.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_v.setAccessibleName("")
        self.vk_v.setAutoFillBackground(False)
        self.vk_v.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_v.setObjectName("vk_v")
        self.vk_b = QtWidgets.QPushButton(Dialog)
        self.vk_b.setGeometry(QtCore.QRect(197, 219, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_b.setFont(font)
        self.vk_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_b.setMouseTracking(False)
        # self.vk_b.setTabletTracking(False)
        self.vk_b.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_b.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_b.setAccessibleName("")
        self.vk_b.setAutoFillBackground(False)
        self.vk_b.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_b.setObjectName("vk_b")
        self.vk_m = QtWidgets.QPushButton(Dialog)
        self.vk_m.setGeometry(QtCore.QRect(290, 219, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_m.setFont(font)
        self.vk_m.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_m.setMouseTracking(False)
        # self.vk_m.setTabletTracking(False)
        self.vk_m.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_m.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_m.setAccessibleName("")
        self.vk_m.setAutoFillBackground(False)
        self.vk_m.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_m.setObjectName("vk_m")
        self.space = QtWidgets.QPushButton(Dialog)
        self.space.setGeometry(QtCore.QRect(150, 249, 181, 40))
        self.space.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.space.setMouseTracking(False)
        # self.space.setTabletTracking(False)
        self.space.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.space.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.space.setAccessibleName("")
        self.space.setAutoFillBackground(False)
        self.space.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.space.setObjectName("space")
        self.backspace = QtWidgets.QPushButton(Dialog)
        self.backspace.setGeometry(QtCore.QRect(430, 219, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.backspace.setFont(font)
        self.backspace.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backspace.setMouseTracking(False)
        # self.backspace.setTabletTracking(False)
        self.backspace.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.backspace.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.backspace.setAccessibleName("")
        self.backspace.setAutoFillBackground(False)
        self.backspace.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.backspace.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/backspace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backspace.setIcon(icon)
        self.backspace.setIconSize(QtCore.QSize(35, 25))
        self.backspace.setObjectName("backspace")
        self.vk_3 = QtWidgets.QPushButton(Dialog)
        self.vk_3.setGeometry(QtCore.QRect(104, 129, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_3.setFont(font)
        self.vk_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_3.setMouseTracking(False)
        # self.vk_3.setTabletTracking(False)
        self.vk_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_3.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_3.setAccessibleName("")
        self.vk_3.setAutoFillBackground(False)
        self.vk_3.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_3.setObjectName("vk_3")
        self.vk_8 = QtWidgets.QPushButton(Dialog)
        self.vk_8.setGeometry(QtCore.QRect(338, 129, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_8.setFont(font)
        self.vk_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_8.setMouseTracking(False)
        # self.vk_8.setTabletTracking(False)
        self.vk_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_8.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_8.setAccessibleName("")
        self.vk_8.setAutoFillBackground(False)
        self.vk_8.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_8.setObjectName("vk_8")
        self.vk_9 = QtWidgets.QPushButton(Dialog)
        self.vk_9.setGeometry(QtCore.QRect(384, 129, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_9.setFont(font)
        self.vk_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_9.setMouseTracking(False)
        # self.vk_9.setTabletTracking(False)
        self.vk_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_9.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_9.setAccessibleName("")
        self.vk_9.setAutoFillBackground(False)
        self.vk_9.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_9.setObjectName("vk_9")
        self.vk_4 = QtWidgets.QPushButton(Dialog)
        self.vk_4.setGeometry(QtCore.QRect(150, 129, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_4.setFont(font)
        self.vk_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_4.setMouseTracking(False)
        # self.vk_4.setTabletTracking(False)
        self.vk_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_4.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_4.setAccessibleName("")
        self.vk_4.setAutoFillBackground(False)
        self.vk_4.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_4.setObjectName("vk_4")
        self.vk_5 = QtWidgets.QPushButton(Dialog)
        self.vk_5.setGeometry(QtCore.QRect(197, 129, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_5.setFont(font)
        self.vk_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_5.setMouseTracking(False)
        # self.vk_5.setTabletTracking(False)
        self.vk_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_5.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_5.setAccessibleName("")
        self.vk_5.setAutoFillBackground(False)
        self.vk_5.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_5.setObjectName("vk_5")
        self.vk_1 = QtWidgets.QPushButton(Dialog)
        self.vk_1.setGeometry(QtCore.QRect(10, 129, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_1.setFont(font)
        self.vk_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_1.setMouseTracking(False)
        # self.vk_1.setTabletTracking(False)
        self.vk_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_1.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_1.setAccessibleName("")
        self.vk_1.setAutoFillBackground(False)
        self.vk_1.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_1.setObjectName("vk_1")
        self.vk_0 = QtWidgets.QPushButton(Dialog)
        self.vk_0.setGeometry(QtCore.QRect(430, 129, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_0.setFont(font)
        self.vk_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_0.setMouseTracking(False)
        # self.vk_0.setTabletTracking(False)
        self.vk_0.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_0.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_0.setAccessibleName("")
        self.vk_0.setAutoFillBackground(False)
        self.vk_0.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_0.setObjectName("vk_0")
        self.vk_2 = QtWidgets.QPushButton(Dialog)
        self.vk_2.setGeometry(QtCore.QRect(56, 129, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_2.setFont(font)
        self.vk_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_2.setMouseTracking(False)
        # self.vk_2.setTabletTracking(False)
        self.vk_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_2.setAccessibleName("")
        self.vk_2.setAutoFillBackground(False)
        self.vk_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_2.setObjectName("vk_2")
        self.vk_6 = QtWidgets.QPushButton(Dialog)
        self.vk_6.setGeometry(QtCore.QRect(244, 129, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_6.setFont(font)
        self.vk_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_6.setMouseTracking(False)
        # self.vk_6.setTabletTracking(False)
        self.vk_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_6.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_6.setAccessibleName("")
        self.vk_6.setAutoFillBackground(False)
        self.vk_6.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_6.setObjectName("vk_6")
        self.vk_7 = QtWidgets.QPushButton(Dialog)
        self.vk_7.setGeometry(QtCore.QRect(290, 129, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_7.setFont(font)
        self.vk_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_7.setMouseTracking(False)
        # self.vk_7.setTabletTracking(False)
        self.vk_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_7.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_7.setAccessibleName("")
        self.vk_7.setAutoFillBackground(False)
        self.vk_7.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_7.setObjectName("vk_7")
        self.vk_underscore = QtWidgets.QPushButton(Dialog)
        self.vk_underscore.setGeometry(QtCore.QRect(338, 219, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_underscore.setFont(font)
        self.vk_underscore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_underscore.setMouseTracking(False)
        # self.vk_underscore.setTabletTracking(False)
        self.vk_underscore.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_underscore.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_underscore.setAccessibleName("")
        self.vk_underscore.setAutoFillBackground(False)
        self.vk_underscore.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_underscore.setObjectName("vk_underscore")
        self.capsLock = QtWidgets.QPushButton(Dialog)
        self.capsLock.setGeometry(QtCore.QRect(384, 219, 40, 25))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.capsLock.setFont(font)
        self.capsLock.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.capsLock.setMouseTracking(False)
        # self.capsLock.setTabletTracking(False)
        self.capsLock.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.capsLock.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.capsLock.setAccessibleName("")
        self.capsLock.setAutoFillBackground(False)
        self.capsLock.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.capsLock.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/capsLock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.capsLock.setIcon(icon1)
        self.capsLock.setIconSize(QtCore.QSize(30, 30))
        self.capsLock.setObjectName("capsLock")
        self.delAll = QtWidgets.QPushButton(Dialog)
        self.delAll.setGeometry(QtCore.QRect(420, 60, 51, 41))
        self.delAll.setStyleSheet("background-color: None;")
        self.delAll.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/delStrings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delAll.setIcon(icon2)
        self.delAll.setIconSize(QtCore.QSize(41, 30))
        self.delAll.setObjectName("delAll")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New project"))
        self.lblNovoProjeto.setText(_translate("Dialog", "New project"))
        self.lblNome.setText(_translate("Dialog", "Name:"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
        self.btnCreate.setText(_translate("Dialog", "Create"))
        self.vk_q.setText(_translate("Dialog", "q"))
        self.vk_w.setText(_translate("Dialog", "w"))
        self.vk_e.setText(_translate("Dialog", "e"))
        self.vk_r.setText(_translate("Dialog", "r"))
        self.vk_t.setText(_translate("Dialog", "t"))
        self.vk_y.setText(_translate("Dialog", "y"))
        self.vk_u.setText(_translate("Dialog", "u"))
        self.vk_p.setText(_translate("Dialog", "p"))
        self.vk_a.setText(_translate("Dialog", "a"))
        self.vk_s.setText(_translate("Dialog", "s"))
        self.vk_i.setText(_translate("Dialog", "i"))
        self.vk_o.setText(_translate("Dialog", "o"))
        self.vk_d.setText(_translate("Dialog", "d"))
        self.vk_f.setText(_translate("Dialog", "f"))
        self.vk_j.setText(_translate("Dialog", "j"))
        self.vk_k.setText(_translate("Dialog", "k"))
        self.vk_l.setText(_translate("Dialog", "l"))
        self.vk_g.setText(_translate("Dialog", "g"))
        self.vk_h.setText(_translate("Dialog", "h"))
        self.vk_cc.setText(_translate("Dialog", "ç"))
        self.vk_z.setText(_translate("Dialog", "z"))
        self.vk_c.setText(_translate("Dialog", "c"))
        self.vk_n.setText(_translate("Dialog", "n"))
        self.vk_x.setText(_translate("Dialog", "x"))
        self.vk_v.setText(_translate("Dialog", "v"))
        self.vk_b.setText(_translate("Dialog", "b"))
        self.vk_m.setText(_translate("Dialog", "m"))
        self.space.setText(_translate("Dialog", "|_____________________|"))
        self.vk_3.setText(_translate("Dialog", "3"))
        self.vk_8.setText(_translate("Dialog", "8"))
        self.vk_9.setText(_translate("Dialog", "9"))
        self.vk_4.setText(_translate("Dialog", "4"))
        self.vk_5.setText(_translate("Dialog", "5"))
        self.vk_1.setText(_translate("Dialog", "1"))
        self.vk_0.setText(_translate("Dialog", "0"))
        self.vk_2.setText(_translate("Dialog", "2"))
        self.vk_6.setText(_translate("Dialog", "6"))
        self.vk_7.setText(_translate("Dialog", "7"))
        self.vk_underscore.setText(_translate("Dialog", "_"))
        self.capsLock.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Caps</p><p>Lock</p></body></html>"))


class guiCalib(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 320)
        Dialog.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.btnAccept = QtWidgets.QPushButton(Dialog)
        self.btnAccept.setGeometry(QtCore.QRect(290, 270, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAccept.setFont(font)
        self.btnAccept.setStyleSheet("background-color: none;")
        self.btnAccept.setObjectName("btnAccept")
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(70, 270, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("background-color: none;")
        self.btnCancel.setObjectName("btnCancel")
        self.lblDnTime = QtWidgets.QLabel(Dialog)
        self.lblDnTime.setGeometry(QtCore.QRect(130, 10, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblDnTime.setFont(font)
        self.lblDnTime.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblDnTime.setObjectName("lblDnTime")
        self.lblStrSens = QtWidgets.QLabel(Dialog)
        self.lblStrSens.setGeometry(QtCore.QRect(80, 200, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblStrSens.setFont(font)
        self.lblStrSens.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblStrSens.setObjectName("lblStrSens")
        self.lblSens = QtWidgets.QLabel(Dialog)
        self.lblSens.setGeometry(QtCore.QRect(80, 230, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblSens.setFont(font)
        self.lblSens.setStyleSheet("color: rgb(172, 229, 255);")
        self.lblSens.setObjectName("lblSens")
        self.lblCorr = QtWidgets.QLabel(Dialog)
        self.lblCorr.setGeometry(QtCore.QRect(300, 230, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblCorr.setFont(font)
        self.lblCorr.setStyleSheet("color: rgb(255, 0, 0);")
        self.lblCorr.setObjectName("lblCorr")
        self.lblStrCorr = QtWidgets.QLabel(Dialog)
        self.lblStrCorr.setGeometry(QtCore.QRect(300, 200, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblStrCorr.setFont(font)
        self.lblStrCorr.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblStrCorr.setObjectName("lblStrCorr")
        self.MaxLevel = QtWidgets.QLabel(Dialog)
        self.MaxLevel.setGeometry(QtCore.QRect(148, 97, 111, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.MaxLevel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.MaxLevel.setFont(font)
        self.MaxLevel.setObjectName("MaxLevel")
        self.dB = QtWidgets.QLabel(Dialog)
        self.dB.setGeometry(QtCore.QRect(278, 97, 41, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.dB.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.dB.setFont(font)
        self.dB.setObjectName("dB")
        self.Hz = QtWidgets.QLabel(Dialog)
        self.Hz.setGeometry(QtCore.QRect(278, 157, 41, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Hz.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Hz.setFont(font)
        self.Hz.setObjectName("Hz")
        self.freqMax = QtWidgets.QLabel(Dialog)
        self.freqMax.setGeometry(QtCore.QRect(198, 157, 71, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.freqMax.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.freqMax.setFont(font)
        self.freqMax.setObjectName("freqMax")
        self.Hz_2 = QtWidgets.QLabel(Dialog)
        self.Hz_2.setGeometry(QtCore.QRect(148, 157, 31, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Hz_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Hz_2.setFont(font)
        self.Hz_2.setObjectName("Hz_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calibration"))
        self.btnAccept.setText(_translate("Dialog", "Accept"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
        self.lblDnTime.setText(_translate("gui_Calib", "<html><head/><body><p align=\"center\">Performing calibration...</p><p align=\"center\">Please wait --:--</p></body></html>"))
        self.lblStrSens.setText(_translate("Dialog", "Sensitivity"))
        self.lblSens.setText(_translate("Dialog", "1,00000"))
        self.lblCorr.setText(_translate("Dialog", "1,00000"))
        self.lblStrCorr.setText(_translate("Dialog", "Correction"))
        self.MaxLevel.setText(_translate("Dialog", "100,00"))
        self.dB.setText(_translate("Dialog", "dB"))
        self.Hz.setText(_translate("Dialog", "Hz"))
        self.freqMax.setText(_translate("Dialog", "10000"))
        self.Hz_2.setText(_translate("Dialog", "at"))



class guiSave(object):
    def setupUi(self, SaveAll):
        SaveAll.setObjectName("SaveAll")
        SaveAll.resize(364, 160)
        SaveAll.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.lbl_yesorno = QtWidgets.QLabel(SaveAll)
        self.lbl_yesorno.setGeometry(QtCore.QRect(30, 20, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_yesorno.setFont(font)
        self.lbl_yesorno.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_yesorno.setObjectName("lbl_yesorno")
        self.btnSaveAll = QtWidgets.QPushButton(SaveAll)
        self.btnSaveAll.setGeometry(QtCore.QRect(50, 100, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnSaveAll.setFont(font)
        self.btnSaveAll.setStyleSheet("background-color: none;")
        self.btnSaveAll.setObjectName("btnSaveAll")
        self.btnNoSaveAll = QtWidgets.QPushButton(SaveAll)
        self.btnNoSaveAll.setGeometry(QtCore.QRect(220, 100, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnNoSaveAll.setFont(font)
        self.btnNoSaveAll.setStyleSheet("background-color: none;")
        self.btnNoSaveAll.setObjectName("btnNoSaveAll")

        self.retranslateUi(SaveAll)
        QtCore.QMetaObject.connectSlotsByName(SaveAll)

    def retranslateUi(self, SaveAll):
        _translate = QtCore.QCoreApplication.translate
        SaveAll.setWindowTitle(_translate("SaveAll", "Save"))
        self.lbl_yesorno.setText(_translate("SaveAll", "Do you want to save reference signals\n"
"         (Measurement and calibration)?"))
        self.btnSaveAll.setText(_translate("SaveAll", "Yes"))
        self.btnNoSaveAll.setText(_translate("SaveAll", "No"))



class guiAbout(object):
    def setupUi(self, gui_About):
        gui_About.setObjectName("gui_About")
        gui_About.resize(480, 320)
        gui_About.setAutoFillBackground(False)
        gui_About.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.label = QtWidgets.QLabel(gui_About)
        self.label.setGeometry(QtCore.QRect(10, 20, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(172, 229, 255);")
        self.label.setObjectName("label")
        self.btnOk = QtWidgets.QPushButton(gui_About)
        self.btnOk.setGeometry(QtCore.QRect(180, 260, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnOk.setFont(font)
        self.btnOk.setStyleSheet("background-color: rgb(172, 229, 255);")
        self.btnOk.setObjectName("btnOk")
        self.label_2 = QtWidgets.QLabel(gui_About)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 440, 140))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_2.setToolTip("")
        self.label_2.setWhatsThis("")
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(gui_About)
        QtCore.QMetaObject.connectSlotsByName(gui_About)

    def retranslateUi(self, gui_About):
        _translate = QtCore.QCoreApplication.translate
        gui_About.setWindowTitle(_translate("gui_About", "About the project"))
        self.label.setToolTip(_translate("gui_About", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setWhatsThis(_translate("gui_About", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("gui_About", "           Low-cost Sound Level Meter"))
        self.btnOk.setText(_translate("gui_About", "Ok"))
        self.label_2.setText(_translate("gui_About", "Software-hardware developed by Leonardo Jacomussi, as part of the Final Project of the Acoustical Engineering undergraduate course at the Federal University of Santa Maria (UFSM). Supervised by prof. William D'Andrea Fonseca. \n"
"\n"
"Note: simple software version.\n"
"\n"
"Release: 06/2020"))