# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget

class guiMNPS(object):
    def setupUi(self, gui_MNPS):
        gui_MNPS.setObjectName("gui_MNPS")
        gui_MNPS.resize(800, 430)
        gui_MNPS.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnNewproject = QtWidgets.QPushButton(gui_MNPS)
        self.btnNewproject.setGeometry(QtCore.QRect(560, 90, 40, 40))
        self.btnNewproject.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnNewproject.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/NewProject.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewproject.setIcon(icon)
        self.btnNewproject.setIconSize(QtCore.QSize(40, 40))
        self.btnNewproject.setObjectName("btnNewproject")
        self.lblDateinfo = QtWidgets.QLabel(gui_MNPS)
        self.lblDateinfo.setGeometry(QtCore.QRect(560, 10, 171, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lblDateinfo.setFont(font)
        self.lblDateinfo.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblDateinfo.setObjectName("lblDateinfo")
        self.btnSetup = QtWidgets.QPushButton(gui_MNPS)
        self.btnSetup.setGeometry(QtCore.QRect(610, 90, 40, 40))
        self.btnSetup.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnSetup.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/Setup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSetup.setIcon(icon1)
        self.btnSetup.setIconSize(QtCore.QSize(40, 40))
        self.btnSetup.setObjectName("btnSetup")
        self.lcdLImin = QtWidgets.QLabel(gui_MNPS)
        self.lcdLImin.setGeometry(QtCore.QRect(730, 290, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lcdLImin.setFont(font)
        self.lcdLImin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLImin.setObjectName("lcdLImin")
        self.lblUnits = QtWidgets.QLabel(gui_MNPS)
        self.lblUnits.setGeometry(QtCore.QRect(520, 190, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lblUnits.setFont(font)
        self.lblUnits.setWhatsThis("")
        self.lblUnits.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblUnits.setObjectName("lblUnits")
        self.btnPlay = QtWidgets.QPushButton(gui_MNPS)
        self.btnPlay.setGeometry(QtCore.QRect(120, 80, 60, 55))
        self.btnPlay.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnPlay.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlay.setIcon(icon2)
        self.btnPlay.setIconSize(QtCore.QSize(60, 55))
        self.btnPlay.setObjectName("btnPlay")
        self.lblMaxLevel_2 = QtWidgets.QLabel(gui_MNPS)
        self.lblMaxLevel_2.setGeometry(QtCore.QRect(630, 290, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblMaxLevel_2.setFont(font)
        self.lblMaxLevel_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblMaxLevel_2.setObjectName("lblMaxLevel_2")
        self.lcdLevel_global = QtWidgets.QLabel(gui_MNPS)
        self.lcdLevel_global.setGeometry(QtCore.QRect(610, 190, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lcdLevel_global.setFont(font)
        self.lcdLevel_global.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLevel_global.setObjectName("lcdLevel_global")
        self.btnInfo = QtWidgets.QPushButton(gui_MNPS)
        self.btnInfo.setGeometry(QtCore.QRect(710, 90, 40, 40))
        self.btnInfo.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnInfo.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInfo.setIcon(icon3)
        self.btnInfo.setIconSize(QtCore.QSize(40, 40))
        self.btnInfo.setObjectName("btnInfo")
        self.lblMinLevel_2 = QtWidgets.QLabel(gui_MNPS)
        self.lblMinLevel_2.setGeometry(QtCore.QRect(770, 290, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblMinLevel_2.setFont(font)
        self.lblMinLevel_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblMinLevel_2.setObjectName("lblMinLevel_2")
        self.lblDurationinfo = QtWidgets.QLabel(gui_MNPS)
        self.lblDurationinfo.setGeometry(QtCore.QRect(230, 50, 81, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblDurationinfo.setFont(font)
        self.lblDurationinfo.setStyleSheet("color: rgb(255, 0, 0);")
        self.lblDurationinfo.setObjectName("lblDurationinfo")
        self.lblLImax = QtWidgets.QLabel(gui_MNPS)
        self.lblLImax.setGeometry(QtCore.QRect(520, 290, 56, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lblLImax.setFont(font)
        self.lblLImax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLImax.setObjectName("lblLImax")
        self.btnCalibrate = QtWidgets.QPushButton(gui_MNPS)
        self.btnCalibrate.setGeometry(QtCore.QRect(660, 90, 40, 40))
        self.btnCalibrate.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnCalibrate.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/Calibrate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCalibrate.setIcon(icon4)
        self.btnCalibrate.setIconSize(QtCore.QSize(40, 40))
        self.btnCalibrate.setObjectName("btnCalibrate")
        self.lcdLImax = QtWidgets.QLabel(gui_MNPS)
        self.lcdLImax.setGeometry(QtCore.QRect(580, 290, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lcdLImax.setFont(font)
        self.lcdLImax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLImax.setObjectName("lcdLImax")
        self.lblTemplateInfo = QtWidgets.QLabel(gui_MNPS)
        self.lblTemplateInfo.setGeometry(QtCore.QRect(550, 150, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblTemplateInfo.setFont(font)
        self.lblTemplateInfo.setStyleSheet("color: rgb(172, 229, 255);")
        self.lblTemplateInfo.setObjectName("lblTemplateInfo")
        self.btnSave = QtWidgets.QPushButton(gui_MNPS)
        self.btnSave.setGeometry(QtCore.QRect(460, 20, 40, 40))
        self.btnSave.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnSave.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon5)
        self.btnSave.setIconSize(QtCore.QSize(40, 40))
        self.btnSave.setObjectName("btnSave")
        self.btnStop = QtWidgets.QPushButton(gui_MNPS)
        self.btnStop.setGeometry(QtCore.QRect(350, 80, 60, 55))
        self.btnStop.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnStop.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/Stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon6)
        self.btnStop.setIconSize(QtCore.QSize(60, 55))
        self.btnStop.setObjectName("btnStop")
        self.lblUnits_2 = QtWidgets.QLabel(gui_MNPS)
        self.lblUnits_2.setGeometry(QtCore.QRect(740, 190, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lblUnits_2.setFont(font)
        self.lblUnits_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblUnits_2.setObjectName("lblUnits_2")
        self.lblLImin = QtWidgets.QLabel(gui_MNPS)
        self.lblLImin.setGeometry(QtCore.QRect(670, 290, 56, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblLImin.setFont(font)
        self.lblLImin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLImin.setObjectName("lblLImin")
        self.lblProjectinfo = QtWidgets.QLabel(gui_MNPS)
        self.lblProjectinfo.setGeometry(QtCore.QRect(110, 20, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblProjectinfo.setFont(font)
        self.lblProjectinfo.setWhatsThis("")
        self.lblProjectinfo.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblProjectinfo.setObjectName("lblProjectinfo")
        self.btnDelete = QtWidgets.QPushButton(gui_MNPS)
        self.btnDelete.setGeometry(QtCore.QRect(10, 20, 40, 40))
        self.btnDelete.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnDelete.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/Delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon7)
        self.btnDelete.setIconSize(QtCore.QSize(40, 40))
        self.btnDelete.setObjectName("btnDelete")
        # self.graphicOctave = QtWidgets.QGraphicsView(gui_MNPS)
        # self.graphicOctave.setGeometry(QtCore.QRect(0, 150, 501, 281))
        # self.graphicOctave.setObjectName("graphicOctave")
        self.graphicOctave = PlotWidget(gui_MNPS)
        self.graphicOctave.setGeometry(QtCore.QRect(0, 150, 511, 281))
        self.graphicOctave.setObjectName("graphicOctave")
        
        self.lcdLFmin = QtWidgets.QLabel(gui_MNPS)
        self.lcdLFmin.setGeometry(QtCore.QRect(730, 340, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lcdLFmin.setFont(font)
        self.lcdLFmin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLFmin.setObjectName("lcdLFmin")
        self.lcdLFmax = QtWidgets.QLabel(gui_MNPS)
        self.lcdLFmax.setGeometry(QtCore.QRect(580, 340, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lcdLFmax.setFont(font)
        self.lcdLFmax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLFmax.setObjectName("lcdLFmax")
        self.lblLFmax = QtWidgets.QLabel(gui_MNPS)
        self.lblLFmax.setGeometry(QtCore.QRect(520, 340, 56, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lblLFmax.setFont(font)
        self.lblLFmax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLFmax.setObjectName("lblLFmax")
        self.lblMaxLevel_3 = QtWidgets.QLabel(gui_MNPS)
        self.lblMaxLevel_3.setGeometry(QtCore.QRect(630, 340, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblMaxLevel_3.setFont(font)
        self.lblMaxLevel_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblMaxLevel_3.setObjectName("lblMaxLevel_3")
        self.lblLFmin = QtWidgets.QLabel(gui_MNPS)
        self.lblLFmin.setGeometry(QtCore.QRect(670, 340, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblLFmin.setFont(font)
        self.lblLFmin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLFmin.setObjectName("lblLFmin")
        self.lblMinLevel_3 = QtWidgets.QLabel(gui_MNPS)
        self.lblMinLevel_3.setGeometry(QtCore.QRect(770, 340, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblMinLevel_3.setFont(font)
        self.lblMinLevel_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblMinLevel_3.setObjectName("lblMinLevel_3")
        self.lcdLSmin = QtWidgets.QLabel(gui_MNPS)
        self.lcdLSmin.setGeometry(QtCore.QRect(730, 390, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lcdLSmin.setFont(font)
        self.lcdLSmin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLSmin.setObjectName("lcdLSmin")
        self.lcdLSmax = QtWidgets.QLabel(gui_MNPS)
        self.lcdLSmax.setGeometry(QtCore.QRect(580, 390, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lcdLSmax.setFont(font)
        self.lcdLSmax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdLSmax.setObjectName("lcdLSmax")
        self.lblLSmax = QtWidgets.QLabel(gui_MNPS)
        self.lblLSmax.setGeometry(QtCore.QRect(520, 390, 56, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lblLSmax.setFont(font)
        self.lblLSmax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLSmax.setObjectName("lblLSmax")
        self.lblMaxLevel_4 = QtWidgets.QLabel(gui_MNPS)
        self.lblMaxLevel_4.setGeometry(QtCore.QRect(630, 390, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblMaxLevel_4.setFont(font)
        self.lblMaxLevel_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblMaxLevel_4.setObjectName("lblMaxLevel_4")
        self.lblLSmin = QtWidgets.QLabel(gui_MNPS)
        self.lblLSmin.setGeometry(QtCore.QRect(670, 390, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblLSmin.setFont(font)
        self.lblLSmin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLSmin.setObjectName("lblLSmin")
        self.lblMinLevel_4 = QtWidgets.QLabel(gui_MNPS)
        self.lblMinLevel_4.setGeometry(QtCore.QRect(770, 390, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        self.lblMinLevel_4.setFont(font)
        self.lblMinLevel_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblMinLevel_4.setObjectName("lblMinLevel_4")
        self.btnQuit = QtWidgets.QPushButton(gui_MNPS)
        self.btnQuit.setGeometry(QtCore.QRect(740, 20, 40, 40))
        self.btnQuit.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.btnQuit.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnQuit.setIcon(icon8)
        self.btnQuit.setIconSize(QtCore.QSize(40, 40))
        self.btnQuit.setObjectName("btnQuit")

        self.retranslateUi(gui_MNPS)
        QtCore.QMetaObject.connectSlotsByName(gui_MNPS)

    def retranslateUi(self, winMNPS, Freqweighting='Z', template='Reverberation time', inTimeweighting='T'):
        _translate = QtCore.QCoreApplication.translate
        winMNPS.setWindowTitle(_translate("winMNPS", "Sound Level Meter (Acoustical Engineering - UFSM)"))
        self.lblDateinfo.setText(_translate("winMNPS", "DD/MM/AA - Hr:Min:Sec"))
        self.lcdLImin.setText(_translate("winMNPS", "--,--"))
        self.lblUnits.setText(_translate("winMNPS", "<html><head/><body><p>L<span style=\" vertical-align:sub;\">"+Freqweighting+"eq,"+inTimeweighting+"</span></p></body></html>"))
        self.lblMaxLevel_2.setText(_translate("winMNPS", " dB"))
        self.lcdLevel_global.setText(_translate("winMNPS", "00,00"))
        self.lblMinLevel_2.setText(_translate("winMNPS", " dB"))
        self.lblDurationinfo.setText(_translate("winMNPS", "Min:Sec"))
        self.lblLImax.setText(_translate("winMNPS", "<html><head/><body><p><span style=\" font-size:14pt;\">L</span><span style=\" font-size:14pt; vertical-align:sub;\">"+Freqweighting+"max,I</span></p></body></html>"))
        self.lcdLImax.setText(_translate("winMNPS", "--,--"))
        self.lblTemplateInfo.setText(_translate("winMNPS", "<html><head/><body><p align=\"center\">"+template+"</p></body></html>"))
        self.lblUnits_2.setText(_translate("winMNPS", "dB"))
        self.lblLImin.setText(_translate("winMNPS", "<html><head/><body><p><span style=\" font-size:14pt;\">L</span><span style=\" font-size:14pt; vertical-align:sub;\">"+Freqweighting+"min,I</span></p></body></html>"))
        self.lblProjectinfo.setText(_translate("winMNPS", "<html><head/><body><p align=\"center\">Nome do projeto - Ensaio 00</p></body></html>"))
        self.lcdLFmin.setText(_translate("winMNPS", "--,--"))
        self.lcdLFmax.setText(_translate("winMNPS", "--,--"))
        self.lblLFmax.setText(_translate("winMNPS", "<html><head/><body><p><span style=\" font-size:14pt;\">L</span><span style=\" font-size:14pt; vertical-align:sub;\">"+Freqweighting+"max,F</span></p></body></html>"))
        self.lblMaxLevel_3.setText(_translate("winMNPS", " dB"))
        self.lblLFmin.setText(_translate("winMNPS", "<html><head/><body><p><span style=\" font-size:14pt;\">L</span><span style=\" font-size:14pt; vertical-align:sub;\">"+Freqweighting+"min,F</span></p></body></html>"))
        self.lblMinLevel_3.setText(_translate("winMNPS", " dB"))
        self.lcdLSmin.setText(_translate("winMNPS", "--,--"))
        self.lcdLSmax.setText(_translate("winMNPS", "--,--"))
        self.lblLSmax.setText(_translate("winMNPS", "<html><head/><body><p><span style=\" font-size:14pt;\">L</span><span style=\" font-size:14pt; vertical-align:sub;\">"+Freqweighting+"max,S</span></p></body></html>"))
        self.lblMaxLevel_4.setText(_translate("winMNPS", " dB"))
        self.lblLSmin.setText(_translate("winMNPS", "<html><head/><body><p><span style=\" font-size:14pt;\">L</span><span style=\" font-size:14pt; vertical-align:sub;\">"+Freqweighting+"min,S</span></p></body></html>"))
        self.lblMinLevel_4.setText(_translate("winMNPS", " dB"))


class guiCalib(object):
    def setupUi(self, gui_Calib):
        gui_Calib.setObjectName("gui_Calib")
        gui_Calib.resize(800, 430)
        gui_Calib.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.btnAccept = QtWidgets.QPushButton(gui_Calib)
        self.btnAccept.setGeometry(QtCore.QRect(670, 370, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAccept.setFont(font)
        self.btnAccept.setStyleSheet("background-color: none;")
        self.btnAccept.setObjectName("btnAccept")
        self.btnCancel = QtWidgets.QPushButton(gui_Calib)
        self.btnCancel.setGeometry(QtCore.QRect(510, 370, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("background-color: none;")
        self.btnCancel.setObjectName("btnCancel")
        self.lblDnTime = QtWidgets.QLabel(gui_Calib)
        self.lblDnTime.setGeometry(QtCore.QRect(40, 10, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblDnTime.setFont(font)
        self.lblDnTime.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblDnTime.setObjectName("lblDnTime")
        self.lblStrSens = QtWidgets.QLabel(gui_Calib)
        self.lblStrSens.setGeometry(QtCore.QRect(510, 280, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblStrSens.setFont(font)
        self.lblStrSens.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblStrSens.setObjectName("lblStrSens")
        self.lblSens = QtWidgets.QLabel(gui_Calib)
        self.lblSens.setGeometry(QtCore.QRect(510, 309, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblSens.setFont(font)
        self.lblSens.setStyleSheet("color: rgb(172, 229, 255);")
        self.lblSens.setObjectName("lblSens")
        # self.graphicCalibration = QtWidgets.QGraphicsView(gui_Calib)
        # self.graphicCalibration.setGeometry(QtCore.QRect(10, 84, 481, 331))
        # self.graphicCalibration.setObjectName("graphicCalibration")
        self.graphicCalibration =PlotWidget(gui_Calib)
        self.graphicCalibration.setGeometry(QtCore.QRect(10, 84, 481, 331))
        self.graphicCalibration.setObjectName("graphicCalibration")
        
        self.lblCorr = QtWidgets.QLabel(gui_Calib)
        self.lblCorr.setGeometry(QtCore.QRect(670, 310, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblCorr.setFont(font)
        self.lblCorr.setStyleSheet("color: rgb(255, 0, 0);")
        self.lblCorr.setObjectName("lblCorr")
        self.lblStrCorr = QtWidgets.QLabel(gui_Calib)
        self.lblStrCorr.setGeometry(QtCore.QRect(670, 280, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblStrCorr.setFont(font)
        self.lblStrCorr.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblStrCorr.setObjectName("lblStrCorr")
        self.freqMax = QtWidgets.QLabel(gui_Calib)
        self.freqMax.setGeometry(QtCore.QRect(610, 190, 71, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.freqMax.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.freqMax.setFont(font)
        self.freqMax.setObjectName("freqMax")
        self.Hz = QtWidgets.QLabel(gui_Calib)
        self.Hz.setGeometry(QtCore.QRect(690, 190, 41, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Hz.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Hz.setFont(font)
        self.Hz.setObjectName("Hz")
        self.Hz_2 = QtWidgets.QLabel(gui_Calib)
        self.Hz_2.setGeometry(QtCore.QRect(560, 190, 31, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Hz_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Hz_2.setFont(font)
        self.Hz_2.setObjectName("Hz_2")
        self.dB = QtWidgets.QLabel(gui_Calib)
        self.dB.setGeometry(QtCore.QRect(690, 130, 41, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.dB.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.dB.setFont(font)
        self.dB.setObjectName("dB")
        self.MaxLevel = QtWidgets.QLabel(gui_Calib)
        self.MaxLevel.setGeometry(QtCore.QRect(560, 130, 111, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.MaxLevel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.MaxLevel.setFont(font)
        self.MaxLevel.setObjectName("MaxLevel")

        self.retranslateUi(gui_Calib)
        QtCore.QMetaObject.connectSlotsByName(gui_Calib)

    def retranslateUi(self, gui_Calib):
        _translate = QtCore.QCoreApplication.translate
        gui_Calib.setWindowTitle(_translate("gui_Calib", "Calibration"))
        self.btnAccept.setText(_translate("gui_Calib", "Accept"))
        self.btnCancel.setText(_translate("gui_Calib", "Cancel"))
        self.lblDnTime.setText(_translate("gui_Calib", "<html><head/><body><p align=\"center\">Performing calibration...</p><p align=\"center\">Please wait --:--</p></body></html>"))
        self.lblStrSens.setText(_translate("gui_Calib", "Sensitivity"))
        self.lblSens.setText(_translate("gui_Calib", "--,-- mV/Pa"))
        self.lblCorr.setText(_translate("gui_Calib", "--,-- dB"))
        self.lblStrCorr.setText(_translate("gui_Calib", "Correction"))
        self.freqMax.setText(_translate("gui_Calib", "---,--"))
        self.Hz.setText(_translate("gui_Calib", "Hz"))
        self.Hz_2.setText(_translate("gui_Calib", "at"))
        self.dB.setText(_translate("gui_Calib", "dB"))
        self.MaxLevel.setText(_translate("gui_Calib", "--,--"))


class guiProject(object):
    def setupUi(self, gui_Project):
        gui_Project.setObjectName("gui_Project")
        gui_Project.resize(800, 430)
        gui_Project.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.lblNovoProjeto = QtWidgets.QLabel(gui_Project)
        self.lblNovoProjeto.setGeometry(QtCore.QRect(320, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lblNovoProjeto.setFont(font)
        self.lblNovoProjeto.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblNovoProjeto.setObjectName("lblNovoProjeto")
        self.lblNome = QtWidgets.QLabel(gui_Project)
        self.lblNome.setGeometry(QtCore.QRect(60, 60, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblNome.setFont(font)
        self.lblNome.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblNome.setObjectName("lblNome")
        self.entryProjectname = QtWidgets.QTextEdit(gui_Project)
        self.entryProjectname.setGeometry(QtCore.QRect(130, 60, 571, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.entryProjectname.setFont(font)
        self.entryProjectname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entryProjectname.setObjectName("entryProjectname")
        self.btnCancel = QtWidgets.QPushButton(gui_Project)
        self.btnCancel.setGeometry(QtCore.QRect(60, 360, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("background-color: None;")
        self.btnCancel.setObjectName("btnCancel")
        self.btnCreate = QtWidgets.QPushButton(gui_Project)
        self.btnCreate.setGeometry(QtCore.QRect(619, 360, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCreate.setFont(font)
        self.btnCreate.setStyleSheet("background-color: None;")
        self.btnCreate.setObjectName("btnCreate")
        self.vk_q = QtWidgets.QPushButton(gui_Project)
        self.vk_q.setGeometry(QtCore.QRect(60, 180, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_q.setFont(font)
        self.vk_q.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_q.setMouseTracking(False)
        # self.vk_q.setTabletTracking(False)
        self.vk_q.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_q.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_q.setAccessibleName("")
        self.vk_q.setAutoFillBackground(False)
        self.vk_q.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_q.setObjectName("vk_q")
        self.vk_w = QtWidgets.QPushButton(gui_Project)
        self.vk_w.setGeometry(QtCore.QRect(130, 180, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_w.setFont(font)
        self.vk_w.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_w.setMouseTracking(False)
        # self.vk_w.setTabletTracking(False)
        self.vk_w.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_w.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_w.setAccessibleName("")
        self.vk_w.setAutoFillBackground(False)
        self.vk_w.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_w.setObjectName("vk_w")
        self.vk_e = QtWidgets.QPushButton(gui_Project)
        self.vk_e.setGeometry(QtCore.QRect(200, 180, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_e.setFont(font)
        self.vk_e.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_e.setMouseTracking(False)
        # self.vk_e.setTabletTracking(False)
        self.vk_e.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_e.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_e.setAccessibleName("")
        self.vk_e.setAutoFillBackground(False)
        self.vk_e.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_e.setObjectName("vk_e")
        self.vk_r = QtWidgets.QPushButton(gui_Project)
        self.vk_r.setGeometry(QtCore.QRect(270, 180, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_r.setFont(font)
        self.vk_r.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_r.setMouseTracking(False)
        # self.vk_r.setTabletTracking(False)
        self.vk_r.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_r.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_r.setAccessibleName("")
        self.vk_r.setAutoFillBackground(False)
        self.vk_r.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_r.setObjectName("vk_r")
        self.vk_t = QtWidgets.QPushButton(gui_Project)
        self.vk_t.setGeometry(QtCore.QRect(340, 180, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_t.setFont(font)
        self.vk_t.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_t.setMouseTracking(False)
        # self.vk_t.setTabletTracking(False)
        self.vk_t.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_t.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_t.setAccessibleName("")
        self.vk_t.setAutoFillBackground(False)
        self.vk_t.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_t.setObjectName("vk_t")
        self.vk_y = QtWidgets.QPushButton(gui_Project)
        self.vk_y.setGeometry(QtCore.QRect(410, 180, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_y.setFont(font)
        self.vk_y.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_y.setMouseTracking(False)
        # self.vk_y.setTabletTracking(False)
        self.vk_y.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_y.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_y.setAccessibleName("")
        self.vk_y.setAutoFillBackground(False)
        self.vk_y.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_y.setObjectName("vk_y")
        self.vk_u = QtWidgets.QPushButton(gui_Project)
        self.vk_u.setGeometry(QtCore.QRect(480, 180, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_u.setFont(font)
        self.vk_u.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_u.setMouseTracking(False)
        # self.vk_u.setTabletTracking(False)
        self.vk_u.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_u.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_u.setAccessibleName("")
        self.vk_u.setAutoFillBackground(False)
        self.vk_u.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_u.setObjectName("vk_u")
        self.vk_p = QtWidgets.QPushButton(gui_Project)
        self.vk_p.setGeometry(QtCore.QRect(690, 180, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_p.setFont(font)
        self.vk_p.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_p.setMouseTracking(False)
        # self.vk_p.setTabletTracking(False)
        self.vk_p.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_p.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_p.setAccessibleName("")
        self.vk_p.setAutoFillBackground(False)
        self.vk_p.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_p.setObjectName("vk_p")
        self.vk_a = QtWidgets.QPushButton(gui_Project)
        self.vk_a.setGeometry(QtCore.QRect(60, 240, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_a.setFont(font)
        self.vk_a.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_a.setMouseTracking(False)
        # self.vk_a.setTabletTracking(False)
        self.vk_a.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_a.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_a.setAccessibleName("")
        self.vk_a.setAutoFillBackground(False)
        self.vk_a.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_a.setObjectName("vk_a")
        self.vk_s = QtWidgets.QPushButton(gui_Project)
        self.vk_s.setGeometry(QtCore.QRect(130, 240, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_s.setFont(font)
        self.vk_s.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_s.setMouseTracking(False)
        # self.vk_s.setTabletTracking(False)
        self.vk_s.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_s.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_s.setAccessibleName("")
        self.vk_s.setAutoFillBackground(False)
        self.vk_s.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_s.setObjectName("vk_s")
        self.vk_i = QtWidgets.QPushButton(gui_Project)
        self.vk_i.setGeometry(QtCore.QRect(550, 180, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_i.setFont(font)
        self.vk_i.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_i.setMouseTracking(False)
        # self.vk_i.setTabletTracking(False)
        self.vk_i.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_i.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_i.setAccessibleName("")
        self.vk_i.setAutoFillBackground(False)
        self.vk_i.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_i.setObjectName("vk_i")
        self.vk_o = QtWidgets.QPushButton(gui_Project)
        self.vk_o.setGeometry(QtCore.QRect(620, 180, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_o.setFont(font)
        self.vk_o.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_o.setMouseTracking(False)
        # self.vk_o.setTabletTracking(False)
        self.vk_o.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_o.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_o.setAccessibleName("")
        self.vk_o.setAutoFillBackground(False)
        self.vk_o.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_o.setObjectName("vk_o")
        self.vk_d = QtWidgets.QPushButton(gui_Project)
        self.vk_d.setGeometry(QtCore.QRect(200, 240, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_d.setFont(font)
        self.vk_d.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_d.setMouseTracking(False)
        # self.vk_d.setTabletTracking(False)
        self.vk_d.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_d.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_d.setAccessibleName("")
        self.vk_d.setAutoFillBackground(False)
        self.vk_d.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_d.setObjectName("vk_d")
        self.vk_f = QtWidgets.QPushButton(gui_Project)
        self.vk_f.setGeometry(QtCore.QRect(270, 240, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_f.setFont(font)
        self.vk_f.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_f.setMouseTracking(False)
        # self.vk_f.setTabletTracking(False)
        self.vk_f.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_f.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_f.setAccessibleName("")
        self.vk_f.setAutoFillBackground(False)
        self.vk_f.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_f.setObjectName("vk_f")
        self.vk_j = QtWidgets.QPushButton(gui_Project)
        self.vk_j.setGeometry(QtCore.QRect(480, 240, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_j.setFont(font)
        self.vk_j.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_j.setMouseTracking(False)
        # self.vk_j.setTabletTracking(False)
        self.vk_j.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_j.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_j.setAccessibleName("")
        self.vk_j.setAutoFillBackground(False)
        self.vk_j.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_j.setObjectName("vk_j")
        self.vk_k = QtWidgets.QPushButton(gui_Project)
        self.vk_k.setGeometry(QtCore.QRect(550, 240, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_k.setFont(font)
        self.vk_k.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_k.setMouseTracking(False)
        # self.vk_k.setTabletTracking(False)
        self.vk_k.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_k.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_k.setAccessibleName("")
        self.vk_k.setAutoFillBackground(False)
        self.vk_k.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_k.setObjectName("vk_k")
        self.vk_l = QtWidgets.QPushButton(gui_Project)
        self.vk_l.setGeometry(QtCore.QRect(620, 240, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_l.setFont(font)
        self.vk_l.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_l.setMouseTracking(False)
        # self.vk_l.setTabletTracking(False)
        self.vk_l.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_l.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_l.setAccessibleName("")
        self.vk_l.setAutoFillBackground(False)
        self.vk_l.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_l.setObjectName("vk_l")
        self.vk_g = QtWidgets.QPushButton(gui_Project)
        self.vk_g.setGeometry(QtCore.QRect(340, 240, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_g.setFont(font)
        self.vk_g.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_g.setMouseTracking(False)
        # self.vk_g.setTabletTracking(False)
        self.vk_g.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_g.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_g.setAccessibleName("")
        self.vk_g.setAutoFillBackground(False)
        self.vk_g.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_g.setObjectName("vk_g")
        self.vk_h = QtWidgets.QPushButton(gui_Project)
        self.vk_h.setGeometry(QtCore.QRect(410, 240, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_h.setFont(font)
        self.vk_h.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_h.setMouseTracking(False)
        # self.vk_h.setTabletTracking(False)
        self.vk_h.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_h.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_h.setAccessibleName("")
        self.vk_h.setAutoFillBackground(False)
        self.vk_h.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_h.setObjectName("vk_h")
        self.vk_cc = QtWidgets.QPushButton(gui_Project)
        self.vk_cc.setGeometry(QtCore.QRect(690, 240, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_cc.setFont(font)
        self.vk_cc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_cc.setMouseTracking(False)
        # self.vk_cc.setTabletTracking(False)
        self.vk_cc.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_cc.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_cc.setAccessibleName("")
        self.vk_cc.setAutoFillBackground(False)
        self.vk_cc.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_cc.setObjectName("vk_cc")
        self.vk_z = QtWidgets.QPushButton(gui_Project)
        self.vk_z.setGeometry(QtCore.QRect(60, 300, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_z.setFont(font)
        self.vk_z.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_z.setMouseTracking(False)
        # self.vk_z.setTabletTracking(False)
        self.vk_z.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_z.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_z.setAccessibleName("")
        self.vk_z.setAutoFillBackground(False)
        self.vk_z.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_z.setObjectName("vk_z")
        self.vk_c = QtWidgets.QPushButton(gui_Project)
        self.vk_c.setGeometry(QtCore.QRect(200, 300, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_c.setFont(font)
        self.vk_c.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_c.setMouseTracking(False)
        # self.vk_c.setTabletTracking(False)
        self.vk_c.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_c.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_c.setAccessibleName("")
        self.vk_c.setAutoFillBackground(False)
        self.vk_c.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_c.setObjectName("vk_c")
        self.vk_n = QtWidgets.QPushButton(gui_Project)
        self.vk_n.setGeometry(QtCore.QRect(410, 300, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_n.setFont(font)
        self.vk_n.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_n.setMouseTracking(False)
        # self.vk_n.setTabletTracking(False)
        self.vk_n.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_n.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_n.setAccessibleName("")
        self.vk_n.setAutoFillBackground(False)
        self.vk_n.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_n.setObjectName("vk_n")
        self.vk_x = QtWidgets.QPushButton(gui_Project)
        self.vk_x.setGeometry(QtCore.QRect(130, 300, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_x.setFont(font)
        self.vk_x.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_x.setMouseTracking(False)
        # self.vk_x.setTabletTracking(False)
        self.vk_x.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_x.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_x.setAccessibleName("")
        self.vk_x.setAutoFillBackground(False)
        self.vk_x.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_x.setObjectName("vk_x")
        self.vk_v = QtWidgets.QPushButton(gui_Project)
        self.vk_v.setGeometry(QtCore.QRect(270, 300, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_v.setFont(font)
        self.vk_v.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_v.setMouseTracking(False)
        # self.vk_v.setTabletTracking(False)
        self.vk_v.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_v.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_v.setAccessibleName("")
        self.vk_v.setAutoFillBackground(False)
        self.vk_v.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_v.setObjectName("vk_v")
        self.vk_b = QtWidgets.QPushButton(gui_Project)
        self.vk_b.setGeometry(QtCore.QRect(340, 300, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_b.setFont(font)
        self.vk_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_b.setMouseTracking(False)
        # self.vk_b.setTabletTracking(False)
        self.vk_b.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_b.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_b.setAccessibleName("")
        self.vk_b.setAutoFillBackground(False)
        self.vk_b.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_b.setObjectName("vk_b")
        self.vk_m = QtWidgets.QPushButton(gui_Project)
        self.vk_m.setGeometry(QtCore.QRect(480, 300, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_m.setFont(font)
        self.vk_m.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_m.setMouseTracking(False)
        # self.vk_m.setTabletTracking(False)
        self.vk_m.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_m.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_m.setAccessibleName("")
        self.vk_m.setAutoFillBackground(False)
        self.vk_m.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_m.setObjectName("vk_m")
        self.space = QtWidgets.QPushButton(gui_Project)
        self.space.setGeometry(QtCore.QRect(200, 360, 411, 40))
        self.space.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.space.setMouseTracking(False)
        # self.space.setTabletTracking(False)
        self.space.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.space.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.space.setAccessibleName("")
        self.space.setAutoFillBackground(False)
        self.space.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.space.setObjectName("space")
        self.backspace = QtWidgets.QPushButton(gui_Project)
        self.backspace.setGeometry(QtCore.QRect(690, 300, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.backspace.setFont(font)
        self.backspace.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backspace.setMouseTracking(False)
        # self.backspace.setTabletTracking(False)
        self.backspace.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.backspace.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.backspace.setAccessibleName("")
        self.backspace.setAutoFillBackground(False)
        self.backspace.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.backspace.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/backspace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backspace.setIcon(icon)
        self.backspace.setIconSize(QtCore.QSize(50, 40))
        self.backspace.setObjectName("backspace")
        self.vk_3 = QtWidgets.QPushButton(gui_Project)
        self.vk_3.setGeometry(QtCore.QRect(200, 120, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_3.setFont(font)
        self.vk_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_3.setMouseTracking(False)
        # self.vk_3.setTabletTracking(False)
        self.vk_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_3.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_3.setAccessibleName("")
        self.vk_3.setAutoFillBackground(False)
        self.vk_3.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_3.setObjectName("vk_3")
        self.vk_8 = QtWidgets.QPushButton(gui_Project)
        self.vk_8.setGeometry(QtCore.QRect(550, 120, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_8.setFont(font)
        self.vk_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_8.setMouseTracking(False)
        # self.vk_8.setTabletTracking(False)
        self.vk_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_8.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_8.setAccessibleName("")
        self.vk_8.setAutoFillBackground(False)
        self.vk_8.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_8.setObjectName("vk_8")
        self.vk_9 = QtWidgets.QPushButton(gui_Project)
        self.vk_9.setGeometry(QtCore.QRect(620, 120, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_9.setFont(font)
        self.vk_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_9.setMouseTracking(False)
        # self.vk_9.setTabletTracking(False)
        self.vk_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_9.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_9.setAccessibleName("")
        self.vk_9.setAutoFillBackground(False)
        self.vk_9.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_9.setObjectName("vk_9")
        self.vk_4 = QtWidgets.QPushButton(gui_Project)
        self.vk_4.setGeometry(QtCore.QRect(270, 120, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_4.setFont(font)
        self.vk_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_4.setMouseTracking(False)
        # self.vk_4.setTabletTracking(False)
        self.vk_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_4.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_4.setAccessibleName("")
        self.vk_4.setAutoFillBackground(False)
        self.vk_4.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_4.setObjectName("vk_4")
        self.vk_5 = QtWidgets.QPushButton(gui_Project)
        self.vk_5.setGeometry(QtCore.QRect(340, 120, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_5.setFont(font)
        self.vk_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_5.setMouseTracking(False)
        # self.vk_5.setTabletTracking(False)
        self.vk_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_5.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_5.setAccessibleName("")
        self.vk_5.setAutoFillBackground(False)
        self.vk_5.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_5.setObjectName("vk_5")
        self.vk_1 = QtWidgets.QPushButton(gui_Project)
        self.vk_1.setGeometry(QtCore.QRect(60, 120, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_1.setFont(font)
        self.vk_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_1.setMouseTracking(False)
        # self.vk_1.setTabletTracking(False)
        self.vk_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_1.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_1.setAccessibleName("")
        self.vk_1.setAutoFillBackground(False)
        self.vk_1.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_1.setObjectName("vk_1")
        self.vk_0 = QtWidgets.QPushButton(gui_Project)
        self.vk_0.setGeometry(QtCore.QRect(690, 120, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_0.setFont(font)
        self.vk_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_0.setMouseTracking(False)
        # self.vk_0.setTabletTracking(False)
        self.vk_0.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_0.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_0.setAccessibleName("")
        self.vk_0.setAutoFillBackground(False)
        self.vk_0.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_0.setObjectName("vk_0")
        self.vk_2 = QtWidgets.QPushButton(gui_Project)
        self.vk_2.setGeometry(QtCore.QRect(130, 120, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_2.setFont(font)
        self.vk_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_2.setMouseTracking(False)
        # self.vk_2.setTabletTracking(False)
        self.vk_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_2.setAccessibleName("")
        self.vk_2.setAutoFillBackground(False)
        self.vk_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_2.setObjectName("vk_2")
        self.vk_6 = QtWidgets.QPushButton(gui_Project)
        self.vk_6.setGeometry(QtCore.QRect(410, 120, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_6.setFont(font)
        self.vk_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_6.setMouseTracking(False)
        # self.vk_6.setTabletTracking(False)
        self.vk_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_6.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_6.setAccessibleName("")
        self.vk_6.setAutoFillBackground(False)
        self.vk_6.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_6.setObjectName("vk_6")
        self.vk_7 = QtWidgets.QPushButton(gui_Project)
        self.vk_7.setGeometry(QtCore.QRect(480, 120, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_7.setFont(font)
        self.vk_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_7.setMouseTracking(False)
        # self.vk_7.setTabletTracking(False)
        self.vk_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_7.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_7.setAccessibleName("")
        self.vk_7.setAutoFillBackground(False)
        self.vk_7.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_7.setObjectName("vk_7")
        self.vk_underscore = QtWidgets.QPushButton(gui_Project)
        self.vk_underscore.setGeometry(QtCore.QRect(550, 300, 60, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.vk_underscore.setFont(font)
        self.vk_underscore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk_underscore.setMouseTracking(False)
        # self.vk_underscore.setTabletTracking(False)
        self.vk_underscore.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vk_underscore.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.vk_underscore.setAccessibleName("")
        self.vk_underscore.setAutoFillBackground(False)
        self.vk_underscore.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.vk_underscore.setObjectName("vk_underscore")
        self.capsLock = QtWidgets.QPushButton(gui_Project)
        self.capsLock.setGeometry(QtCore.QRect(620, 300, 61, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.capsLock.setFont(font)
        self.capsLock.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.capsLock.setMouseTracking(False)
        # self.capsLock.setTabletTracking(False)
        self.capsLock.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.capsLock.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.capsLock.setAccessibleName("")
        self.capsLock.setAutoFillBackground(False)
        self.capsLock.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.capsLock.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/capsLock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.capsLock.setIcon(icon1)
        self.capsLock.setIconSize(QtCore.QSize(61, 50))
        self.capsLock.setObjectName("capsLock")
        self.delAll = QtWidgets.QPushButton(gui_Project)
        self.delAll.setGeometry(QtCore.QRect(700, 60, 51, 41))
        self.delAll.setStyleSheet("background-color: None;")
        self.delAll.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/Delete_noclick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delAll.setIcon(icon2)
        self.delAll.setIconSize(QtCore.QSize(51, 40))
        self.delAll.setObjectName("delAll")

        self.retranslateUi(gui_Project)
        QtCore.QMetaObject.connectSlotsByName(gui_Project)

    def retranslateUi(self, gui_Project):
        _translate = QtCore.QCoreApplication.translate
        gui_Project.setWindowTitle(_translate("gui_Project", "New project"))
        self.lblNovoProjeto.setText(_translate("gui_Project", "New project"))
        self.lblNome.setText(_translate("gui_Project", "Name:"))
        self.btnCancel.setText(_translate("gui_Project", "Cancel"))
        self.btnCreate.setText(_translate("gui_Project", "Create"))
        self.vk_q.setText(_translate("gui_Project", "q"))
        self.vk_w.setText(_translate("gui_Project", "w"))
        self.vk_e.setText(_translate("gui_Project", "e"))
        self.vk_r.setText(_translate("gui_Project", "r"))
        self.vk_t.setText(_translate("gui_Project", "t"))
        self.vk_y.setText(_translate("gui_Project", "y"))
        self.vk_u.setText(_translate("gui_Project", "u"))
        self.vk_p.setText(_translate("gui_Project", "p"))
        self.vk_a.setText(_translate("gui_Project", "a"))
        self.vk_s.setText(_translate("gui_Project", "s"))
        self.vk_i.setText(_translate("gui_Project", "i"))
        self.vk_o.setText(_translate("gui_Project", "o"))
        self.vk_d.setText(_translate("gui_Project", "d"))
        self.vk_f.setText(_translate("gui_Project", "f"))
        self.vk_j.setText(_translate("gui_Project", "j"))
        self.vk_k.setText(_translate("gui_Project", "k"))
        self.vk_l.setText(_translate("gui_Project", "l"))
        self.vk_g.setText(_translate("gui_Project", "g"))
        self.vk_h.setText(_translate("gui_Project", "h"))
        self.vk_cc.setText(_translate("gui_Project", "ç"))
        self.vk_z.setText(_translate("gui_Project", "z"))
        self.vk_c.setText(_translate("gui_Project", "c"))
        self.vk_n.setText(_translate("gui_Project", "n"))
        self.vk_x.setText(_translate("gui_Project", "x"))
        self.vk_v.setText(_translate("gui_Project", "v"))
        self.vk_b.setText(_translate("gui_Project", "b"))
        self.vk_m.setText(_translate("gui_Project", "m"))
        self.space.setText(_translate("gui_Project", "|__________________________________________________|"))
        self.vk_3.setText(_translate("gui_Project", "3"))
        self.vk_8.setText(_translate("gui_Project", "8"))
        self.vk_9.setText(_translate("gui_Project", "9"))
        self.vk_4.setText(_translate("gui_Project", "4"))
        self.vk_5.setText(_translate("gui_Project", "5"))
        self.vk_1.setText(_translate("gui_Project", "1"))
        self.vk_0.setText(_translate("gui_Project", "0"))
        self.vk_2.setText(_translate("gui_Project", "2"))
        self.vk_6.setText(_translate("gui_Project", "6"))
        self.vk_7.setText(_translate("gui_Project", "7"))
        self.vk_underscore.setText(_translate("gui_Project", "_"))
        self.capsLock.setWhatsThis(_translate("gui_Project", "<html><head/><body><p>Caps</p><p>Lock</p></body></html>"))



class guiAbout(object):
    def setupUi(self, gui_About):
        gui_About.setObjectName("gui_About")
        gui_About.resize(480, 320)
        gui_About.setAutoFillBackground(False)
        gui_About.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.label = QtWidgets.QLabel(gui_About)
        self.label.setGeometry(QtCore.QRect(10, 20, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(172, 229, 255);")
        self.label.setObjectName("label")
        self.btnOk = QtWidgets.QPushButton(gui_About)
        self.btnOk.setGeometry(QtCore.QRect(180, 260, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnOk.setFont(font)
        self.btnOk.setStyleSheet("background-color: rgb(172, 229, 255);")
        self.btnOk.setObjectName("btnOk")
        self.label_2 = QtWidgets.QLabel(gui_About)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 440, 140))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_2.setToolTip("")
        self.label_2.setWhatsThis("")
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(gui_About)
        QtCore.QMetaObject.connectSlotsByName(gui_About)

    def retranslateUi(self, gui_About):
        _translate = QtCore.QCoreApplication.translate
        gui_About.setWindowTitle(_translate("gui_About", "About the project"))
        self.label.setToolTip(_translate("gui_About", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setWhatsThis(_translate("gui_About", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("gui_About", "           Low-cost Sound Level Meter"))
        self.btnOk.setText(_translate("gui_About", "Ok"))
        self.label_2.setText(_translate("gui_About", "Software-hardware developed by Leonardo Jacomussi, as part of the Final Project of the Acoustical Engineering undergraduate course at the Federal University of Santa Maria (UFSM). Supervised by prof. William D'Andrea Fonseca. \n"
"\n"
"Note: full version of the software.\n"
"\n"
"Release: 06/2020"))



class guiSetup(object):
    def setupUi(self, gui_Setup):
        gui_Setup.setObjectName("gui_Setup")
        gui_Setup.setEnabled(True)
        gui_Setup.resize(800, 430)
        gui_Setup.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.lbl_Duration_AnalEspec = QtWidgets.QLabel(gui_Setup)
        self.lbl_Duration_AnalEspec.setGeometry(QtCore.QRect(20, 270, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Duration_AnalEspec.setFont(font)
        self.lbl_Duration_AnalEspec.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_Duration_AnalEspec.setObjectName("lbl_Duration_AnalEspec")
        self.inFreqmin = QtWidgets.QSpinBox(gui_Setup)
        self.inFreqmin.setGeometry(QtCore.QRect(70, 90, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inFreqmin.setFont(font)
        self.inFreqmin.setStyleSheet("background-color: none;")
        self.inFreqmin.setMinimum(20)
        self.inFreqmin.setMaximum(250)
        self.inFreqmin.setSingleStep(20)
        self.inFreqmin.setDisplayIntegerBase(10)
        self.inFreqmin.setObjectName("inFreqmin")
        self.lbl_BandOctave = QtWidgets.QLabel(gui_Setup)
        self.lbl_BandOctave.setGeometry(QtCore.QRect(20, 160, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_BandOctave.setFont(font)
        self.lbl_BandOctave.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_BandOctave.setObjectName("lbl_BandOctave")
        self.lblTimeintegration = QtWidgets.QLabel(gui_Setup)
        self.lblTimeintegration.setGeometry(QtCore.QRect(20, 210, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblTimeintegration.setFont(font)
        self.lblTimeintegration.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblTimeintegration.setObjectName("lblTimeintegration")
        self.inFreqmax = QtWidgets.QSpinBox(gui_Setup)
        self.inFreqmax.setGeometry(QtCore.QRect(250, 90, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inFreqmax.setFont(font)
        self.inFreqmax.setStyleSheet("background-color: none;")
        self.inFreqmax.setMinimum(16000)
        self.inFreqmax.setMaximum(20000)
        self.inFreqmax.setSingleStep(500)
        self.inFreqmax.setProperty("value", 16000)
        self.inFreqmax.setObjectName("inFreqmax")
        self.btnCancel = QtWidgets.QPushButton(gui_Setup)
        self.btnCancel.setGeometry(QtCore.QRect(80, 380, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("background-color: none;")
        self.btnCancel.setObjectName("btnCancel")
        self.lblPondfreq = QtWidgets.QLabel(gui_Setup)
        self.lblPondfreq.setGeometry(QtCore.QRect(20, 330, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblPondfreq.setFont(font)
        self.lblPondfreq.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblPondfreq.setObjectName("lblPondfreq")
        self.lbl_FaixaFreq = QtWidgets.QLabel(gui_Setup)
        self.lbl_FaixaFreq.setGeometry(QtCore.QRect(120, 60, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_FaixaFreq.setFont(font)
        self.lbl_FaixaFreq.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_FaixaFreq.setObjectName("lbl_FaixaFreq")
        self.lbl_FreqMax = QtWidgets.QLabel(gui_Setup)
        self.lbl_FreqMax.setGeometry(QtCore.QRect(200, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_FreqMax.setFont(font)
        self.lbl_FreqMax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_FreqMax.setObjectName("lbl_FreqMax")
        self.frameCalibration = QtWidgets.QFrame(gui_Setup)
        self.frameCalibration.setGeometry(QtCore.QRect(490, 340, 291, 81))
        self.frameCalibration.setStyleSheet("background-color: rgb(82, 255, 235);")
        self.frameCalibration.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCalibration.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCalibration.setObjectName("frameCalibration")
        self.btnCalibrate = QtWidgets.QPushButton(self.frameCalibration)
        self.btnCalibrate.setGeometry(QtCore.QRect(90, 40, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnCalibrate.setFont(font)
        self.btnCalibrate.setStyleSheet("background-color: none;")
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap("../../../.designer/backup/icon/Calibrate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.btnCalibrate.setIcon(icon)
        self.btnCalibrate.setObjectName("btnCalibrate")
        self.lblFTCalibration = QtWidgets.QLabel(self.frameCalibration)
        self.lblFTCalibration.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblFTCalibration.setFont(font)
        self.lblFTCalibration.setObjectName("lblFTCalibration")
        self.lblFTC = QtWidgets.QLabel(self.frameCalibration)
        self.lblFTC.setGeometry(QtCore.QRect(180, 10, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblFTC.setFont(font)
        self.lblFTC.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFTC.setObjectName("lblFTC")
        self.lbl_Template = QtWidgets.QLabel(gui_Setup)
        self.lbl_Template.setGeometry(QtCore.QRect(20, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Template.setFont(font)
        self.lbl_Template.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_Template.setObjectName("lbl_Template")
        self.groupBox_SinalExcit = QtWidgets.QGroupBox(gui_Setup)
        self.groupBox_SinalExcit.setEnabled(True)
        self.groupBox_SinalExcit.setGeometry(QtCore.QRect(490, 10, 291, 331))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_SinalExcit.setFont(font)
        self.groupBox_SinalExcit.setStyleSheet("background-color: rgb(172, 229, 255);")
        self.groupBox_SinalExcit.setFlat(True)
        self.groupBox_SinalExcit.setCheckable(False)
        self.groupBox_SinalExcit.setChecked(False)
        self.groupBox_SinalExcit.setObjectName("groupBox_SinalExcit")
        self.lbl_startMargin = QtWidgets.QLabel(self.groupBox_SinalExcit)
        self.lbl_startMargin.setGeometry(QtCore.QRect(10, 160, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_startMargin.setFont(font)
        self.lbl_startMargin.setObjectName("lbl_startMargin")
        self.inStopmargin = QtWidgets.QSpinBox(self.groupBox_SinalExcit)
        self.inStopmargin.setGeometry(QtCore.QRect(180, 210, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inStopmargin.setFont(font)
        self.inStopmargin.setStyleSheet("background-color: None")
        self.inStopmargin.setMaximum(300)
        self.inStopmargin.setProperty("value", 5)
        self.inStopmargin.setObjectName("inStopmargin")
        self.lbl_Duration_SinalExcit = QtWidgets.QLabel(self.groupBox_SinalExcit)
        self.lbl_Duration_SinalExcit.setGeometry(QtCore.QRect(10, 90, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Duration_SinalExcit.setFont(font)
        self.lbl_Duration_SinalExcit.setObjectName("lbl_Duration_SinalExcit")
        self.lbl_stopMargin = QtWidgets.QLabel(self.groupBox_SinalExcit)
        self.lbl_stopMargin.setGeometry(QtCore.QRect(10, 220, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_stopMargin.setFont(font)
        self.lbl_stopMargin.setObjectName("lbl_stopMargin")
        self.lbl_Metodo = QtWidgets.QLabel(self.groupBox_SinalExcit)
        self.lbl_Metodo.setGeometry(QtCore.QRect(10, 40, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Metodo.setFont(font)
        self.lbl_Metodo.setObjectName("lbl_Metodo")
        self.inStartmargin = QtWidgets.QSpinBox(self.groupBox_SinalExcit)
        self.inStartmargin.setGeometry(QtCore.QRect(180, 150, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inStartmargin.setFont(font)
        self.inStartmargin.setStyleSheet("background-color: None")
        self.inStartmargin.setMaximum(120)
        self.inStartmargin.setProperty("value", 5)
        self.inStartmargin.setObjectName("inStartmargin")
        self.inDurationSignal = QtWidgets.QSpinBox(self.groupBox_SinalExcit)
        self.inDurationSignal.setEnabled(True)
        self.inDurationSignal.setGeometry(QtCore.QRect(180, 90, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inDurationSignal.setFont(font)
        self.inDurationSignal.setStyleSheet("background-color: None")
        self.inDurationSignal.setMinimum(5)
        self.inDurationSignal.setMaximum(300)
        self.inDurationSignal.setSingleStep(1)
        # self.inDurationSignal.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.inDurationSignal.setProperty("value", 8)
        self.inDurationSignal.setDisplayIntegerBase(10)
        self.inDurationSignal.setObjectName("inDurationSignal")
        self.frame_inMethod = QtWidgets.QFrame(self.groupBox_SinalExcit)
        self.frame_inMethod.setGeometry(QtCore.QRect(110, 30, 171, 51))
        self.frame_inMethod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_inMethod.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inMethod.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inMethod.setObjectName("frame_inMethod")
        self.inMethod = QtWidgets.QComboBox(self.frame_inMethod)
        self.inMethod.setGeometry(QtCore.QRect(0, 0, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.inMethod.setFont(font)
        self.inMethod.setStyleSheet("background-color: None")
        self.inMethod.setObjectName("inMethod")
        self.inMethod.addItem("")
        self.inMethod.addItem("")
        self.inMethod.addItem("")
        self.lbl_average = QtWidgets.QLabel(self.groupBox_SinalExcit)
        self.lbl_average.setGeometry(QtCore.QRect(10, 280, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_average.setFont(font)
        self.lbl_average.setObjectName("lbl_average")
        self.inAverage = QtWidgets.QDoubleSpinBox(self.groupBox_SinalExcit)
        self.inAverage.setGeometry(QtCore.QRect(180, 270, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inAverage.setFont(font)
        self.inAverage.setStyleSheet("background-color: None")
        self.inAverage.setKeyboardTracking(True)
        self.inAverage.setDecimals(0)
        self.inAverage.setMinimum(1.0)
        self.inAverage.setMaximum(30.0)
        self.inAverage.setSingleStep(1.0)
        self.inAverage.setProperty("value", 1.0)
        self.inAverage.setObjectName("inAverage")
        self.btnApply = QtWidgets.QPushButton(gui_Setup)
        self.btnApply.setGeometry(QtCore.QRect(250, 380, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnApply.setFont(font)
        self.btnApply.setStyleSheet("background-color: none;")
        self.btnApply.setObjectName("btnApply")
        self.lbl_FreqMin = QtWidgets.QLabel(gui_Setup)
        self.lbl_FreqMin.setGeometry(QtCore.QRect(20, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_FreqMin.setFont(font)
        self.lbl_FreqMin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_FreqMin.setObjectName("lbl_FreqMin")
        self.frame_template = QtWidgets.QFrame(gui_Setup)
        self.frame_template.setGeometry(QtCore.QRect(120, 10, 351, 51))
        self.frame_template.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_template.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_template.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_template.setObjectName("frame_template")
        self.inTemplate = QtWidgets.QComboBox(self.frame_template)
        self.inTemplate.setEnabled(True)
        self.inTemplate.setGeometry(QtCore.QRect(0, 0, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inTemplate.setFont(font)
        self.inTemplate.setStyleSheet("background-color: none;\n"
"selection-color: rgb(255, 255, 255);")
        self.inTemplate.setDuplicatesEnabled(False)
        self.inTemplate.setFrame(True)
        self.inTemplate.setObjectName("inTemplate")
        self.inTemplate.addItem("")
        # self.inTemplate.addItem("")
        self.frame_inFraction = QtWidgets.QFrame(gui_Setup)
        self.frame_inFraction.setGeometry(QtCore.QRect(369, 141, 101, 51))
        self.frame_inFraction.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_inFraction.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inFraction.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inFraction.setObjectName("frame_inFraction")
        self.inFraction = QtWidgets.QComboBox(self.frame_inFraction)
        self.inFraction.setGeometry(QtCore.QRect(0, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inFraction.setFont(font)
        self.inFraction.setStyleSheet("background-color: none;")
        self.inFraction.setObjectName("inFraction")
        self.inFraction.addItem("")
        self.inFraction.addItem("")
        self.frame_inTimeweighting = QtWidgets.QFrame(gui_Setup)
        self.frame_inTimeweighting.setGeometry(QtCore.QRect(369, 201, 101, 51))
        self.frame_inTimeweighting.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_inTimeweighting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inTimeweighting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inTimeweighting.setObjectName("frame_inTimeweighting")
        self.inTimeweighting = QtWidgets.QComboBox(self.frame_inTimeweighting)
        self.inTimeweighting.setGeometry(QtCore.QRect(0, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inTimeweighting.setFont(font)
        self.inTimeweighting.setStyleSheet("background-color: none;")
        self.inTimeweighting.setObjectName("inTimeweighting")
        self.inTimeweighting.addItem("")
        self.inTimeweighting.addItem("")
        self.inTimeweighting.addItem("")
        self.frame_inFreqweighting = QtWidgets.QFrame(gui_Setup)
        self.frame_inFreqweighting.setGeometry(QtCore.QRect(370, 320, 101, 51))
        self.frame_inFreqweighting.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_inFreqweighting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inFreqweighting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inFreqweighting.setObjectName("frame_inFreqweighting")
        self.inFreqweighting = QtWidgets.QComboBox(self.frame_inFreqweighting)
        self.inFreqweighting.setGeometry(QtCore.QRect(0, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inFreqweighting.setFont(font)
        self.inFreqweighting.setStyleSheet("background-color: none;")
        self.inFreqweighting.setObjectName("inFreqweighting")
        self.inFreqweighting.addItem("")
        self.inFreqweighting.addItem("")
        self.inFreqweighting.addItem("")
        self.inDurationMeasure = QtWidgets.QTimeEdit(gui_Setup)
        self.inDurationMeasure.setGeometry(QtCore.QRect(370, 260, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inDurationMeasure.setFont(font)
        self.inDurationMeasure.setStyleSheet("background-color: None")
        self.inDurationMeasure.setMaximumTime(QtCore.QTime(0, 59, 59))
        self.inDurationMeasure.setMinimumTime(QtCore.QTime(0, 0, 20))
        self.inDurationMeasure.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.inDurationMeasure.setObjectName("inDurationMeasure")

        self.retranslateUi(gui_Setup)
        QtCore.QMetaObject.connectSlotsByName(gui_Setup)

    def retranslateUi(self, gui_Setup):
        _translate = QtCore.QCoreApplication.translate
        gui_Setup.setWindowTitle(_translate("gui_Setup", "Settings"))
        self.lbl_Duration_AnalEspec.setText(_translate("gui_Setup", "Duration:"))
        self.lbl_BandOctave.setText(_translate("gui_Setup", "Octave band:"))
        self.lblTimeintegration.setText(_translate("gui_Setup", "Time weighting:"))
        self.btnCancel.setText(_translate("gui_Setup", "Cancel"))
        self.lblPondfreq.setText(_translate("gui_Setup", "Frequency weighting:"))
        self.lbl_FaixaFreq.setText(_translate("gui_Setup", "Frequency range [Hz]:"))
        self.lbl_FreqMax.setText(_translate("gui_Setup", "Max"))
        self.btnCalibrate.setText(_translate("gui_Setup", "Calibrate"))
        self.lblFTCalibration.setText(_translate("gui_Setup", "Correction:"))
        self.lblFTC.setText(_translate("gui_Setup", "100,00 dB"))
        self.lbl_Template.setText(_translate("gui_Setup", "Template:"))
        self.groupBox_SinalExcit.setTitle(_translate("gui_Setup", "  Excitement signal"))
        self.lbl_startMargin.setText(_translate("gui_Setup", "Escape de\n"
"time [s]:"))
        self.lbl_Duration_SinalExcit.setText(_translate("gui_Setup", "Excitation \n"
"time [s]:"))
        self.lbl_stopMargin.setText(_translate("gui_Setup", "Decay\n"
"time [s]:"))
        self.lbl_Metodo.setText(_translate("gui_Setup", "Type:"))
        self.inMethod.setItemText(0, _translate("gui_Setup", "Exponential Sweep"))
        self.inMethod.setItemText(1, _translate("gui_Setup", "White noise"))
        self.inMethod.setItemText(2, _translate("gui_Setup", "Pink noise"))
        self.lbl_average.setText(_translate("gui_Setup", "Averages:"))
        self.btnApply.setText(_translate("gui_Setup", "Apply"))
        self.lbl_FreqMin.setText(_translate("gui_Setup", "Min"))
        self.inTemplate.setItemText(0, _translate("gui_Setup", "Frequency analysis"))
        # self.inTemplate.setItemText(1, _translate("gui_Setup", "Reverberation time"))
        self.inFraction.setItemText(0, _translate("gui_Setup", "1/1"))
        self.inFraction.setItemText(1, _translate("gui_Setup", "1/3"))
        self.inTimeweighting.setItemText(0, _translate("gui_Setup", "Impulse"))
        self.inTimeweighting.setItemText(1, _translate("gui_Setup", "Fast"))
        self.inTimeweighting.setItemText(2, _translate("gui_Setup", "Slow"))
        self.inFreqweighting.setItemText(0, _translate("gui_Setup", "A"))
        self.inFreqweighting.setItemText(1, _translate("gui_Setup", "C"))
        self.inFreqweighting.setItemText(2, _translate("gui_Setup", "Z"))
        self.inDurationMeasure.setDisplayFormat(_translate("gui_Setup", "mm:ss"))



class guiSave(object):
    def setupUi(self, SaveAll):
        SaveAll.setObjectName("SaveAll")
        SaveAll.resize(364, 160)
        SaveAll.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.lbl_yesorno = QtWidgets.QLabel(SaveAll)
        self.lbl_yesorno.setGeometry(QtCore.QRect(30, 20, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_yesorno.setFont(font)
        self.lbl_yesorno.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_yesorno.setObjectName("lbl_yesorno")
        self.btnSaveAll = QtWidgets.QPushButton(SaveAll)
        self.btnSaveAll.setGeometry(QtCore.QRect(50, 100, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnSaveAll.setFont(font)
        self.btnSaveAll.setStyleSheet("background-color: none;")
        self.btnSaveAll.setObjectName("btnSaveAll")
        self.btnNoSaveAll = QtWidgets.QPushButton(SaveAll)
        self.btnNoSaveAll.setGeometry(QtCore.QRect(220, 100, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnNoSaveAll.setFont(font)
        self.btnNoSaveAll.setStyleSheet("background-color: none;")
        self.btnNoSaveAll.setObjectName("btnNoSaveAll")

        self.retranslateUi(SaveAll)
        QtCore.QMetaObject.connectSlotsByName(SaveAll)

    def retranslateUi(self, SaveAll):
        _translate = QtCore.QCoreApplication.translate
        SaveAll.setWindowTitle(_translate("SaveAll", "Save"))
        self.lbl_yesorno.setText(_translate("SaveAll", "Do you want to save reference signals\n"
"         (Measurement and calibration)?"))
        self.btnSaveAll.setText(_translate("SaveAll", "Yes"))
        self.btnNoSaveAll.setText(_translate("SaveAll", "No"))

